### ISSUE TITLE
Swagger / UI is awailable under beta9 package

### ISSUE THREAD

**Issue by jcob-ross** [asadsahi/AspNetCoreSpa#1]
Hi, I was just browsing around and found this.

RC2 repo is under https://github.com/domaindrivendev/Ahoy

Creating API without swagger is just miserable experience for me, so here you go.

 "Swashbuckle.SwaggerGen": "6.0.0-beta9",
 "Swashbuckle.SwaggerUi": "6.0.0-beta9",

**Comment by asadsahi** [comment]
Thanks @jcob-ross 

I have added support for Swagger.
