### ISSUE TITLE
RxJs DataService

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#103]
About angular and rx again :)

I am trying to achive server side paging,
```
// Model
vm {
    startrow: number;
    pagelength: number;
}

// Service  dataService is same class in this solution...
public getList(vm): Observable<any> {
        return this.dataService.get(this.baseUrl, vm);
    }

// component 
constructor(
        private Service: Service
    ) {
this.Service.getList(this.vm) 
            .subscribe(
            list => {  this.List = list;   },
            error => this.errorMessage = <any>error);

```

How to service refresh list whenever vm updated/changed.

regards

**Comment by m2017atTR** [comment]
I solved via this,

pageChangedEvent(e) {
this.vm.startrow = e;   // startpage
this.Service.getList(this.vm) 
            .subscribe(
            list => {  this.List = list;   },
            error => this.errorMessage = <any>error);
}

sorry for inexperience ....

**Comment by m2017atTR** [comment]
But i becomes headache ...
Multiple times calling ...whenever Observable stream thicks service calls :D lol

Really there is some misunderstanding here :)

How you solve this kind of problem. App Module heas filter and 
sub module has views that takes data via App Module filter...
For communicate i am trying to go with shared service way...

I tryed to use Subcribe also... could not solve...

thanks for any idea..

**Comment by m2017atTR** [comment]
There are tons of tutorials out there that go over the basics of using Redux, but it’s hard to find a lot of info on fitting it all together. Even once your figure out how they all fit together, it can seem like a lot of extra work with little benefit.

 think there must be some kind of this sugar in this solution too...

**Comment by asadsahi** [comment]
@m2017atTR not sure if this is in the scope of this project. You need to rely on finding an example online for server side pagination if that is what you are trying to implement in this project.
