### ISSUE TITLE
Suggestion: Prod documentation

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#105]
@asadsahi 
If that possible, can you please add documentation how to prepare solution for production ...

So can test that way 

thanks.

**Comment by asadsahi** [comment]
@m2017atTR  how about [this ](https://github.com/asadsahi/AspNetCoreSpa/wiki/Production-deployment) wiki? Any improvements, let me know?

**Comment by m2017atTR** [comment]
There is a few kind of publish in .net core 
https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/

According to server and server installation it can variate...

For this project i want to run on linux and ngix, and need https 

this guy is doing great job about his work... Some inspiration dont hurts i think..

https://github.com/ASP-NET-Core-Boilerplate/Templates/blob/master/MVC%206%20API.md

surely , i can help  too.

**Comment by asadsahi** [comment]
@m2017atTR, sure you can improve the wiki I created with any other mechanism for production deployment OR the ones in the wiki. Other may get benefit from this too.

**Comment by asadsahi** [comment]
[Here](https://github.com/asadsahi/AspNetCoreSpa/wiki/Production-deployment) are some basic notes on prod deployment options.
