### ISSUE TITLE
publish to local iis-server

### ISSUE THREAD

**Issue by j-nord** [asadsahi/AspNetCoreSpa#106]
In the development environment it runs fine. 

But when you publish the project to iis-server with webdeploy the paths are not set correctly.

**Comment by asadsahi** [comment]
@j-nord can you explain which paths are you referring to?

**Comment by j-nord** [comment]
You take you projct and make a webdeploy package (path: "test" or other). Then you start you iis-server and import you project. 

When you start your website your project doesn't work, because  the paths are set incorrectly.

**Comment by asadsahi** [comment]
@j-nord, I don't have experience deploying on IIS with webdeploy as a package. I have deployed on azure webapp using web deploy script mentioned in readme or simply deploy on IIS with xcopy. So, not sure I will be able to help you in your specific scenario.

**Comment by kiwiingenuity** [comment]
@j-nord, I'm not sure what paths you are referring to in IIS server.
One catch however is that if you are deploying to IIS and using SQL server, you do need to create permissions in SQL Server Manager, so that the application can access the database.

**Comment by asadsahi** [comment]
deployment to iis work, but webdeploy package isn't in scope of this project, hence closing.
