### ISSUE TITLE
Discussion : Sate management, is really needed or just subjects and behaviours is ok ..

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#107]
... Hi Documentation is needed for Client Project i think,

there is a app-store that implements Store from @ngrx/store 

```
export interface AppState {
    auth: AuthState;
}

const reducers = {
    auth: authReducer
};
```

but

If i go with this way have i think i have to write actions, reducers, ....

Is that possible to do this in siple way... I dont have many screen parts like hotmail or gmail pages...
Just a menu, category tree selected via menu, and filters that affects to views data that comes from API...

**Question :**   
[https://angularspree.firebaseapp.com](https://angularspree.firebaseapp.com)

This guy using sample app with store , added his actions reducers ...
Is this the only way this way ? like this app used for auth state???

thanks for any help.

**Comment by crh225** [comment]
you can manage state using ngrx/store, or what I do is manage state in inject-able services. In my personal project I have an auth.service that gets injected that contains my logged in user/account info.

**Comment by m2017atTR** [comment]
ngrx/store is a must, if application is not consist of 2 components. period.
