### ISSUE TITLE
angular2-google-maps package update

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#108]
Their package is deprecating so, can we add new one..

**Comment by asadsahi** [comment]
@m2017atTR can you create a pull request with the update after verifying the correct version works well?

**Comment by m2017atTR** [comment]
Steps according to  [docs of angular-google-maps](https://github.com/SebastianM/angular-google-maps/blob/master/CHANGELOG.md#breaking-changes)

     > npm uninstall angular2-google-maps
     > npm i @agm/core

app\+examples\google-maps
     remove: import { AgmCoreModule } from 'angular2-google-maps/core';
     add :      import { AgmCoreModule  } from '@agm/core'

app\+examples\google-maps add
```
        <agm-map [latitude]="lat" [longitude]="lng">
        <agm-marker [latitude]="lat" [longitude]="lng"></agm-marker>
         </agm-map>
```

**Comment by asadsahi** [comment]
Thanks @m2017atTR done.
