### ISSUE TITLE
How deloy to azure

### ISSUE THREAD

**Issue by phongptn93** [asadsahi/AspNetCoreSpa#109]
Hello,

How i can deloy to azure,
I changed the file, but why it retains the old version

Thank you

**Comment by m2017atTR** [comment]
For visual studio already there is a config in project also you can look this issue

https://github.com/asadsahi/AspNetCoreSpa/issues/105#issuecomment-302561044

**Comment by phongptn93** [comment]
@m2017atTR : you can clear talk about it ?

**Comment by m2017atTR** [comment]
[https://github.com/asadsahi/AspNetCoreSpa/wiki/Production-deployment](https://github.com/asadsahi/AspNetCoreSpa/wiki/Production-deployment)

**Comment by phongptn93** [comment]
@m2017atTR : Thank you, i have done it :D, via  clear web and update again :D
http://stackoverflow.com/questions/17476525/clean-windows-azure-website/17552723#17552723
But your idea is greate, I will check it <3, Thank you

**Comment by asadsahi** [comment]
Closing as no further action is required.
