### ISSUE TITLE
Typings installation fails

### ISSUE THREAD

**Issue by martinoss** [asadsahi/AspNetCoreSpa#11]
`typings install` fail with following error:

`Unable to read typings for "angular2-beta-to-rc-alias". You should check the entry paths in "typings.d.ts" are up to date`

{
  "globalDependencies": {
    "angular2-beta-to-rc-alias": "file:./node_modules/**@angularclass**/angular2-beta-to-rc-alias/src/beta-17/typings.d.ts",
    "es6-collections": "registry:dt/es6-collections#0.5.1+20160316155526",
    "require": "registry:dt/require#2.1.20+20160316155526",
    "sinon": "registry:dt/sinon#1.16.0+20160517064723"
  }
}

I guess it's because @angularclass is not present in package.json. I'll check it.

**Comment by asadsahi** [comment]
we don't need these typings, however I checked in missing typings for es6promise and jasmine.
