### ISSUE TITLE
aliases for TypeScript

### ISSUE THREAD

**Issue by tograil** [asadsahi/AspNetCoreSpa#114]
Currently I'm trying to merge your snipped with one of my previous works and can't integrate aliases properly. When I try to run build it, it is just don't see it. Which aliases is visible? TypeScript or WebPack? How I should propely configure webpack to have aliases inside?

**Comment by asadsahi** [comment]
@tograil can you please explain what do you mean by aiases?

**Comment by m2017atTR** [comment]
I thin we are talking about this  subject, 

[https://webpack.js.org/configuration/resolve/](https://webpack.js.org/configuration/resolve/)

**Comment by asadsahi** [comment]
more information is required. closing until then.
