### ISSUE TITLE
Node module Failed 

### ISSUE THREAD

**Issue by Josh001** [asadsahi/AspNetCoreSpa#115]
After publishing and uploading to azure i get this error HTTP Error 502.5 - Process Failure so i came back to the publish folder to do dotnet ./Aspnetcorespa.dll but i get the error 
(Call to Node module failed with error: Webpack dev middleware failed because of an error while loading 'aspnet-webpack'. Error was: Error: Cannot find module 'aspnet-webpack'

I have tried several solutions not working and am stuck on deployment

**Comment by Josh001** [comment]
After uninstalling my nodejs and npm also purging all npm packages and reinstalling, i  went to visual stio 2017 then published the project again now it then Works. So my question is what happens to the hosting.json file when am online i.e on azure what happens to the file do i configure the http binding and also do i need to do any configuration on my freshly created web+Sql app on azure

**Comment by asadsahi** [comment]
@Josh001 hosting.json doesn't reflect the URLs in production, you configure the website on azure as normal. Demo site is deployed as normal git push based deployment from azure portal. Try deploying on local IIS to see if it works. Master branch as alot of new changes which should simplify the deployment process. If you can give it another try and let me know if you find any more issues and I am happy to reopen this issue.

Thanks for your patience.
