### ISSUE TITLE
Usage of Beta packages

### ISSUE THREAD

**Issue by KhalilMohammad** [asadsahi/AspNetCoreSpa#116]
Should not all angular and other packages should be stable.
In the packages.json some packages are of beta version.
I would like to know if there is a reason for using beta packages?

**Comment by asadsahi** [comment]
@KhalilMohammad with the quick pace and release cycle of some of these libraries I just wanted to keep up with the latest and greatest of these libraries so that migration becomes easier as soon as library is released. Thats all. :)

Just upgraded angular to current latest.
