### ISSUE TITLE
ɵDomAnimationEngine on 4.2...

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#117]
import {
    ɵAnimation as Animation, AnimationDriver,
    ɵAnimationStyleNormalizer as AnimationStyleNormalizer, ɵDomAnimationEngine as DomAnimationEngine
} from '@angular/animations/browser';

Material 2 and Some custom animations crahed on ɵDomAnimationEngine part.

**Comment by asadsahi** [comment]
@m2017atTR I don't have much knowledge around these apis. If you can provide a reproduction repo to explain in more details. I can try and have a look. Thanks
