### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#118]
Solution is working perfectly about authentication and authorization
refresh token ext. 

When I work today then close computer and came back refresh token is workin properly but if i dont log in again i face with some errors
auth-token.service.ts / startupTokenRefresh crahes on JSON.parse(tokensString)

Question : Is there more thinks to do about JWT on client side ? 
at when jwt time out ask user to continue or logout directly ext.
- How to implement ? where to start.

**Comment by meninjanho4788** [comment]
i have same problem with login, i no see JWT in this project. when user out browser they must login againt.

**Comment by asadsahi** [comment]
@m2017atTR silet refresh is implemented using [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) now. give it another try.
