### ISSUE TITLE
HTTP Error 502.5 - Process Failure

### ISSUE THREAD

**Issue by WanjyDan** [asadsahi/AspNetCoreSpa#119]
I am getting this error when i run 'dotnet ef migrations add "MigrationName"'
![image](https://user-images.githubusercontent.com/23149113/27275065-8c38fc36-54de-11e7-9194-2370430f2935.png)
Please help..

**Comment by m2017atTR** [comment]
'dotnet ef migrations add "MigrationName"'
- remove quotes if you used 

- if u r using visual studio, look at Outpur,Error list, for more detail.

good luck

**Comment by asadsahi** [comment]
@WanjyDan I haven't seen any issues with creating new migrations. if you still had some specific issue with this project please let me know and I can have a look in details.
