### ISSUE TITLE
Deploying to DigitalOcean

### ISSUE THREAD

**Issue by garethstar** [asadsahi/AspNetCoreSpa#120]
All is working great locally.

I can get the dotnet core side of things to deploy but I am failing on the angular. 

i'm using git lab CI CD to build and deploy if that helps.

Does any one have any advice for this please 

Thanks Gareth

**Comment by asadsahi** [comment]
@garethstar I don't have an experience with digital ocean CI. You need to contact their support if and how they support .net core web apps.
