### ISSUE TITLE
Node --version v6.11.1

### ISSUE THREAD

**Issue by yuenon** [asadsahi/AspNetCoreSpa#124]
I am new for ASP.net core.  I tried to start this application.  I got the following messages:    Would you please tell me what I should do
fail: Microsoft.AspNetCore.NodeServices[0]
      (node:2968) DeprecationWarning: loaderUtils.parseQuery() received a non-st
ring value which can be problematic, see https://github.com/webpack/loader-utils
/issues/56
fail: Microsoft.AspNetCore.NodeServices[0]
      parseQuery() will be replaced with getOptions() in the next major version
of loader-utils.
fail: Microsoft.AspNetCore.NodeServices[0]
      (node:2968) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.get
NumberOfModules/mapModules/forEachModule/containsModule instead.

**Comment by asadsahi** [comment]
@yuenon this shouldn't happen anymore. I guess this may have been because of SSR, which is on hold for now. Master has got some enhancements and fixes in it. Give it a try  and let me know if you encounter this again. Thanks.
