### ISSUE TITLE
Screen Width on Wide Screens

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#128]
Hi, Is there a way to get this spa to span the full screen width on wide screen displays please?

**Comment by asadsahi** [comment]
@pvagnini 
Removing class="container" around the appc-container component shows it full screen:

![image](https://user-images.githubusercontent.com/3470892/28781505-321c6cde-7602-11e7-8c49-b01e8c42df39.png)


Is this what you'are trying to achive?

**Comment by pvagnini** [comment]
Yes exactly what I was looking for.

Thanks
