### ISSUE TITLE
could you upgrade this project to .NetCore 2.0 ?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#132]
could you upgrade this project to .NetCore 2.0 or create new project for .Netcore 2.0

Thank you so much.

**Comment by asadsahi** [comment]
@meninjanho4788  I have a branch which is being worked on for .net core 2.0. But there are few dependencies which aren't supported for .net core 2.0 yet. As soon as that branch is stable with all the packages, will make that master.

https://github.com/asadsahi/AspNetCoreSpa/tree/netcore2

**Comment by meninjanho4788** [comment]
thank you @asadsahi  so much.
