### ISSUE TITLE
.NetCore2 branch running error

### ISSUE THREAD

**Issue by sharethl** [asadsahi/AspNetCoreSpa#136]
Can anyone run .net core 2 branch? 
After running those setup commands, the website loaded, after login, register and login buttons are still there. and click them will result in new view been insert in the current page.
![image](https://user-images.githubusercontent.com/1747556/29735386-973e1b94-89c6-11e7-82bf-a185e71cfe30.png)

**Comment by herbat73** [comment]
Yes. Same bug for me with SQL Express.

**Comment by WanjyDan** [comment]
Me too.

**Comment by idilshod87** [comment]
Try change "View/Home/Index.html" file.
        <appc-root asp-prerender-module="ClientApp/dist/main-server"> 
            <div class="app-spinner">
                <i class="fa fa-spinner fa-spin fa-5x" aria-hidden="true"></i>
            </div>
         </appc-root> 
to
    <appc-root asp-ng2-prerender-module="ClientApp/dist/main-server">
        <div class="app-spinner">
            <i class="fa fa-spinner fa-spin fa-5x" aria-hidden="true"></i>
        </div>
    </appc-root>

**Comment by asadsahi** [comment]
looks like this is related to [this](https://github.com/aspnet/JavaScriptServices/issues/1231
)

**Comment by asadsahi** [comment]
this should be fixed now.
