### ISSUE TITLE
webpack-dev-server missing in dev dependencies

### ISSUE THREAD

**Issue by martinoss** [asadsahi/AspNetCoreSpa#14]
Several package.json scripts are referring to the webpack-dev-server

**Comment by asadsahi** [comment]
@martinoss becuase this project was based on angular 2 webpack starter project, It was easier to do some copy paste for the dependencies and scripts. Needs some cleaning. Will look into this.

**Comment by asadsahi** [comment]
@martinoss we don't need webpack-dev-server. As we this is a .net project and webpack is running in .net process. We have to rely on webpack-dev-middleware which .net javascript services project offers. Also, I have removed reference of running dev server and creating dev and production builds using npm scripts as that is something handled by asp.net core javascript services package. Read more [here](https://github.com/aspnet/JavaScriptServices).
