### ISSUE TITLE
Cannot generate new component using Angular CLI

### ISSUE THREAD

**Issue by ARobsonAxco** [asadsahi/AspNetCoreSpa#144]
In the 2.0 branch when I run the following command (to generate a component using angular cli) "ng g c test" I get the following "Error: Could not find an NgModule for the new component. Use the skip-import option to skip importing components in NgModule." 

I found a simple workaround in this article https://programmium.wordpress.com/2017/10/02/ng-add-angular-cli-to-net-core-angular-template/

**Comment by asadsahi** [comment]
@ARobsonAxco this should be fixed now.
