### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by layinka** [asadsahi/AspNetCoreSpa#145]
I really appreciate the work being done on this project. It has made life easier for all of us,i will bet.
I just checked out the netcore2 branch and i can see its already supporting angular 5 rc.

Being that PWA support is one o f the focus of angular 5, is there any chance this project can be adopted for a PWA project? 
Any pointers?

**Comment by asadsahi** [comment]
@layinka hopefully in future more features will be added.  Will add offline support soon. But things like SSR aren't as stable as they should be. any 3rd party library I am trying to implement such as ng-bootstrap or signalr client isn't working well with SSR. But

**Comment by asadsahi** [comment]
@layinka just to update on this one. I am working on part of PWA story to have some performance in this project and implement some initial performance and SEO concepts enhance in this project. So keep an eye on few changes soon.

**Comment by layinka** [comment]
That's great news.
Thanks 

Sent from my Windows Phone

-----Original Message-----

**Comment by kmiskiewicz** [comment]
@asadsahi @layinka maybe you will find this video interesting (or maybe you you have seen it already), it's about future of PWA in Angular  https://www.youtube.com/watch?v=3ZZCCBjuAXU

**Comment by asadsahi** [comment]
This guy is good, haven't seen this video, but he wrote few [articles ](https://medium.com/@webmaxru/a-new-angular-service-worker-creating-automatic-progressive-web-apps-part-1-theory-37d7d7647cc7) recently and gave a talk at angular connect that is upto date with few changes coming in angular-cli for pwa's. Looking forward to have[ cli baked in SPA services](https://github.com/aspnet/JavaScriptServices/issues/1288) which will help with some pwa work in thsi project.

**Comment by R0xtar** [comment]
Maybe [this](https://madskristensen.net/blog/progressive-web-apps-made-easy-with-aspnet-core/) could help.

**Comment by asadsahi** [comment]
@R0xtar there is already WIP [here](https://github.com/asadsahi/AspNetCoreSpa/tree/angularcli). We'll leverage angular's cli's support for SW.

**Comment by asadsahi** [comment]
PWA support added in master now.

**Comment by layinka** [comment]
This is really great news.
Thanks for all the great work

**Comment by pvagnini** [comment]
again i can confirm that if I change register.component,ts to this it works;

 public register(model: IRegisterModel): void {
        this.dataService.post('http://localhost:5000/api/account/register', model)
            .subscribe(() => {
                this.router.navigate(['../registerconfirmation'], { relativeTo: this.route, queryParams: { emailConfirmed: true } });
            });
    }
