### ISSUE TITLE
Update @NGRX to the new version 

### ISSUE THREAD

**Issue by badre429** [asadsahi/AspNetCoreSpa#146]
@ngrx 4.0.0 version hase breaking changes 
the project need refactoring to support the new version

**Comment by asadsahi** [comment]
@badre429 Apologies, that because of my limited grasp over ngrx at the moment, I have to take it out of the project for now. Maybe in near future I will add it again, but for now I will let anyone who has good knowlege of ngrx to add himself.

**Comment by asadsahi** [comment]
Just to add if someone can put some effort in implementing ngrx in the project, happy to receive that through a pull request.
