### ISSUE TITLE
ios 8 safari and android 4.4 chrome 32 support

### ISSUE THREAD

**Issue by wizicer** [asadsahi/AspNetCoreSpa#148]
In up-to-date modern browser, it works without flaw. however, in both ios 8 safari(ipad 4) and android 4.4.4 chrome 32(nexus 7 gen2), it won't work. Both have the similar error:
`Cannot call method apply of undefined`, the undefined means `Object.assign`.
I deem it should be something relates to `assign` method polyfill.

With my limited knowledge about polyfill with webpack, I can't get it to work. Could anyone to help?

**Comment by wizicer** [comment]
Here is my findings:
I follows the guide: <https://angular.io/guide/webpack> very carefully. Then it works, although I'm still not deeply understand how webpack works.

**Comment by asadsahi** [comment]
@wizicer [polyfills.ts](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/polyfills.ts) has some commented out code which explains some polyfill usages for older browsers. Perhaps "import 'core-js/es6/object';" will fix error you mentioned above. I haven't tried that myself, but you better off uncommenting all the polyfills mentioned for IE9 onwards and try again.

Each project have different needs, but I don't plan to add legacy support polyfills as default in this project. Jut to keep the application size as small as possible in future. Happy to help if you find any more issue. :)
