### ISSUE TITLE
How to donate you?

### ISSUE THREAD

**Issue by kmiskiewicz** [asadsahi/AspNetCoreSpa#149]
Thank you so much for really great project. I learnt a lot from your code.  Some newest pattern were difficult to understand but everything what you prepared is awesome. How can we donate you? :-)

**Comment by asadsahi** [comment]
@kmiskiewicz thanks for your kind words. Happy to hear that. :)

If you wanted to donate, I have just created a donation button from paypal at the bottom of this project's main page.

Thanks.

**Comment by kmiskiewicz** [comment]
Done 👍

**Comment by asadsahi** [comment]
Thanks, appreciate that 👍
