### ISSUE TITLE
Controller Authorisation

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#151]
I have used your ASP Core 1.1 project and it has been fantastic thank you so much.

I am now working with ASP Core 2.0 version however when using the project data.service.ts I can only seem hit the controller if I include [AllowAnonymous] in the controller method even when I am logged in properly.

What am I missing please?

**Comment by asadsahi** [comment]
which controller action you are trying to hit?

**Comment by pvagnini** [comment]
I am using my own Get method on the ProfileController that worked fine with the previous ASP Core 1.1 version project.

TypeScript Service uses the data.service.ts in the new project;
     public GetRoles(): Observable<any> {
        return this.dataService.get('api/Profile/GetRoles');
    }

The start of the Controller method is
 [HttpGet("GetRoles")]
        public IActionResult GetRoles()
        {

This same set of code worked with the 1.1 version project. But with the 2.0 version will only appear to work if I include [AllowAnonymous] which is not good as I only want this to be accessible when logged in. I note this version of the data.service.ts is quite different from the previous version?

Thanks for you help.

**Comment by asadsahi** [comment]
@pvagnini thanks for explaining. It looks like a bug. Will update soon.

**Comment by asadsahi** [comment]
@pvagnini [this](https://github.com/asadsahi/AspNetCoreSpa/commit/aa3594fda04568bab7bd06752e90b469dab17e10) should fix this. give a try and let me know if you find any more issues.

Thanks

**Comment by pvagnini** [comment]
Yes this appears to fix the issue.

Once again many thanks.
