### ISSUE TITLE
Modal Confirm

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#153]
Hi asadsahi,

I had a service I was using to provide a Modal confirm dialog an response in the previous version of this Spa. This no longer works and I can't seem to find anything available that does. I assume the changes in Angular 5.0 might be responsible?

Do you have any suggestions for a solution? As any application really needs to support this type of function to confirm deletes etc.

Thanks for your assistance.

**Comment by asadsahi** [comment]
@pvagnini could you please share the screenshot of which modal you are referring to. this project has ng-bootstrap support and its modal is still available to use as per [documentation](https://ng-bootstrap.github.io/#/components/modal/examples).

If you can share code/error you are having I can have a look in details. Closing for now as I cannot think anything specific changed in this project which should affect any dialogues.
