### ISSUE TITLE
Unrecognized argument format: 'migratedb'

### ISSUE THREAD

**Issue by AlejandroFlorin** [asadsahi/AspNetCoreSpa#155]
Get the following error when following instructions at step:

`dotnet run migratedb seeddb`

Error:
> Unrecognized argument format: 'migratedb'

**Comment by asadsahi** [comment]
@AlejandroFlorin appologies for the error. There have been some changes to how project could be dealt with database., Readme instructions might be a little misleading. I will update them at my earliest.

For now have you tried skipping that command as seeding is done automatically.

**Comment by AlejandroFlorin** [comment]
Thanks, Tried running it with just F5 and I get the following:

Error - object reference not set to an instance of an object
Function - SeedDbData 
Line - AddOpenIdConnectOptions(serviceScope, CancellationToken.None).GetAwaiter().GetResult();

**Comment by asadsahi** [comment]
Did you change the connection string or default sqllite setup?

Also, which codebase you are using, latest or a previous one?

**Comment by AlejandroFlorin** [comment]
I just got the latest version, ran through the install steps and keep getting the same error.

**Comment by asadsahi** [comment]
@AlejandroFlorin I have simplified the readme instructions and removed unnecessary stuff. Hopefully they will help understanding DB usage. Let me know if you find any more issues.

**Comment by AlejandroFlorin** [comment]
Did a fresh install again as per the instructions and it all worked. Thanks.
