### ISSUE TITLE
Routing issue

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#156]
First Thanks for great effort.

i am facing one issue.
i change register page and  login page html according my requirement.
but i try to navigate between home and register and login page then old component not removed its pushing old UI or component below each time.
could please give me direction how i can resolve it.
Thanks.

**Comment by kmiskiewicz** [comment]
Check this issue: #152

**Comment by asadsahi** [comment]
@sajidali2444 if you see in current codebase, specifically main.ts [line 32](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/main.ts#L32) should fix this. If you are using a previous version try adding that line.
