### ISSUE TITLE
Milestones and stable version

### ISSUE THREAD

**Issue by netbidev** [asadsahi/AspNetCoreSpa#158]
Hello!

Could you use version management for your project? This project is very useful for our work and version management will be great feature for project.

**Comment by asadsahi** [comment]
@netbidev cool idea. Have you got any plan in your mind how to manage this?

**Comment by asadsahi** [comment]
Basic idea of releases is started with first version tagged. I will try to keep it more up to date and also would like to version based on Semver. Need to investigate if there is an automated way to version the code in github. But for now I will try to put some release numbers manually. Open for any further suggestions and improvements.

Closing it for now.
