### ISSUE TITLE
HMR doesn't update component

### ISSUE THREAD

**Issue by davayd** [asadsahi/AspNetCoreSpa#160]
Hi guys, i cloned repository right now , completed all the 'Installation' points, after all run the project by F5 (VSCode), my browser running localhost:5000 page, everything is working [HMR] connected: 
https://ibb.co/mXjRNm
BUT, when i editing home.component.ts file and save it
https://ibb.co/b9mj8R
HMR module does not fire and does not update anything.
what a strange behavior ??
terminal warninng: 

> (node:13730) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56. parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

**Comment by asadsahi** [comment]
@davayd these are just deprecated warnings from webpack, but shouldn't affect HMR. I have same warnings on my machine. Can you please provide more information of your OS/dotnet version/node version etc?

**Comment by davayd** [comment]
@asadsahi of course:
https://ibb.co/dJ9656

**Comment by asadsahi** [comment]
It looks like Linux OS?

It could be OS specific. Have you got access to any other OS to try if it work? I am only using windows.

**Comment by davayd** [comment]
yes, it's Linux Mint. I have Windows 7 on other diskpart, I'll try to run project from it and to response about behavior

**Comment by davayd** [comment]
An interesting case, and the truth is, my Linux does not fired the HMR module. I close the problem.
p.s. What can be thought about this behavior on Linux?
