### ISSUE TITLE
Notification service

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#161]
Hi,

Notification service not working.
server-side error message coming but the error message in angular is not showing in the popup.
your demo project showing user already exist but in my case, it's not showing server errors.
please help.

**Comment by asadsahi** [comment]
@sajidali2444 can you provide a little more detail. What server errors you are getting? and what are you expecting in notifications service to appear?

**Comment by sajidali2444** [comment]
Sure,
my server returns bad request 400. in this case I want to show error message in the notification as your demo site shows user already exist.
please see attached image
in my case its not working either password wrong or user already exist.

![screenshot-aspnetcorespa azurewebsites net-2017-11-29-21-49-00-492](https://user-images.githubusercontent.com/960620/33387512-4943dbac-d54f-11e7-9e60-aed63890624a.png)

**Comment by asadsahi** [comment]
@sajidali2444 currenty it is preventing based on client side errors. User already exist is a server side error, so in order to see that error I would assume you need to pass all the client side errors first. Isn't that the case?

**Comment by asadsahi** [comment]
closing for now. If further action needed please provide elaborated information as requested.
