### ISSUE TITLE
Error restoring aspnetcore-authentication nuget package

### ISSUE THREAD

**Issue by AlejandroFlorin** [asadsahi/AspNetCoreSpa#162]
Get the following error:

Install-Package : Unable to load the service index for source https://www.myget.org/F/aspnetcore-authentication/api/v3/index.json.
  Response status code does not indicate success: 404 (Feed does not exist.).
At line:1 char:1
+ Install-Package Microsoft.AspNetCore.Authentication -Version 2.0.1

This looks like its a dependency to that package from another specific to AspNetCoreSpa because I can restore  .net core in its entirety (including that package) in a brand new empty studio project.

Edit: Going one at a time, it looks like the following packages are causing the problem:

        <PackageReference Include="AspNet.Security.OAuth.Amazon" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.StackExchange" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.Yahoo" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.Paypal" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.GitHub" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.LinkedIn" Version="2.0.0-*" />
        <PackageReference Include="AspNet.Security.OAuth.Validation" Version="2.0.0-*" />

**Comment by Arpanx** [comment]
<PackageReference Include="OpenIddict" Version="2.0.0-rc2-0775" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="2.0.0-rc2-0775" />
    <PackageReference Include="OpenIddict.Mvc" Version="2.0.0-rc2-0775" />

**Comment by asadsahi** [comment]
@AlejandroFlorin https://github.com/asadsahi/AspNetCoreSpa/commit/a559f21356df999e955b3e8592ad03e4e1e44fe4 should fix the issue. One of the nuget feed was removed. At some point these packages will be updates to final version, but until then one of the myget feed in nuget will still allow pre-release version to be downloaded. let me know if you find anymore issues.

**Comment by AlejandroFlorin** [comment]
Thanks, that fixed it.
