### ISSUE TITLE
Entity Framework Repository

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#164]
one more thing @asadsahi  please help
you have entity base repository like
public class EntityBaseRepository<T> : IEntityBaseRepository<T> where T : class, IEntityBase, new()
i am trying to as PhotoRepository : EntityBaseRepository<IPhotoRepository>
its throws erros can use IPhotoRepository as type parameter.
or please can you give at least one example how to use this class for DB interaction 
as i am trying to implement UnitOfWork pattern

**Comment by asadsahi** [comment]
@sajidali2444 check [this](https://github.com/chsakell/dotnetcore-entityframework-api/tree/master/Scheduler.Data/Repositories) out as an example.

**Comment by n00dl3s** [comment]
I cannot seem to get the included IUnitOfWork to persist changes to the database using the repository pattern. Could you provide an example, or give direction?

https://github.com/asadsahi/AspNetCoreSpa/blob/master/src/AspNetCoreSpa.Infrastructure/IUnitOfWork.cs
