### ISSUE TITLE
Nuget package error

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#165]
c:\program files\dotnet\sdk\2.1.1\Nuget.targets(103,5): error unable to load the service indx for https://www.myget.org/F/aspnetcore-authentication/api/v3/index.json

**Comment by asadsahi** [comment]
Have you tried after getting the latest? There is a change [here ](https://github.com/asadsahi/AspNetCoreSpa/commit/a559f21356df999e955b3e8592ad03e4e1e44fe4)which should've fix this.
