### ISSUE TITLE
api call

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#166]
@asadsahi  can you help me please quick
i am calling my PostAdController method GetCities using dataService get Method
call success but always retrun home html and GetCities method not being called neither break point hit.

your predefined controller method called like Register , Login 

what i am doing wrong
here code.
C#
[Route("api/[controller]")]
    [AllowAnonymous]
    public class PostAdController : BaseController
    {
        private readonly ICityRepository _city;
        public PostAdController(ICityRepository city)
        {
            _city = city;
           }
    

        [HttpGet]
        public IActionResult GetCities()
        {
            var cities = _city.GetAll().ToList();
            return Ok(cities);
        }
}
}

angular

export class HomeComponent implements OnInit {
    cities: City[];
    ngOnInit(): void {
        this.getCities();
    }
    constructor(private dataService: DataService /*, private globalRef: GlobalRef*/) { }

    //public getCities(cities:string) : Observable<StringMap[]> {
    //    console.log(Observable.of(this.globalRef.nativeGlobal.appData.cities));
    //    return Observable.of(this.globalRef.nativeGlobal.appData.cities);
    //}

    private getCities() {
        this.dataService.get<City[]>('api/postAd')
            .subscribe((res: City[]) => {
                console.log(res);
                this.cities = res;
            });
    }
}
i tried GlobalRef but no success. gloabl ref throws wired errors but atleast GetCities from PostController must be called.

**Comment by asadsahi** [comment]
@sajidali2444  try this:

    [HttpGet("")]
    public IActionResult GetCities()
    {
        var cities = _city.GetAll().ToList();
        return Ok(cities);
    }

**Comment by asadsahi** [comment]
closing for now. escalate if further action needed.
