### ISSUE TITLE
Glimpse Node

### ISSUE THREAD

**Issue by no1ross** [asadsahi/AspNetCoreSpa#167]
Not an issue, but a request.  It would be really nice to see Glimpse Node installed and working with timelines etc. in this template.  BTW thank you very much for this template.

**Comment by asadsahi** [comment]
@no1ross thanks for appreciation.

Glimpse Node is for node based projects as I understand. There used to be an asp.net Glimpse extension, but can't see any .net core compatible yet. If you find any useful profiler tools for dev times please share and I will consider adding it.
