### ISSUE TITLE
Call to external API

### ISSUE THREAD

**Issue by mayorquin** [asadsahi/AspNetCoreSpa#168]
Hello,

I'm trying to call an external API but I'm getting the error:

Response for preflight has invalid HTTP status code 404

Request Method:OPTIONS
Status Code:404 Not Found

This happens with all externals API's. I tested using the Angular template form VS2017 and it works.

Do you have any idea what could be happening with your template? Or I missing something?

**Comment by asadsahi** [comment]
@mayorquin , send me screenshot of the error you get. I suspect this could around the security middlewares added in the project.

**Comment by mayorquin** [comment]
Thanks for your response... It was an error related with http headers.
