### ISSUE TITLE
Can't load project properly

### ISSUE THREAD

**Issue by marcossapp** [asadsahi/AspNetCoreSpa#169]
I followed all the steps and when i start in Visual studio the console.log shows _Error: In this configuration Angular requires Zone.js_

Is this project still valid?

**Comment by asadsahi** [comment]
@marcossapp I am unable to reproduce this. I have just ran fresh code for master and the project ran fine. I guess you are seeing this issue without any modifications? Please provide more details of error like screenshot and your environment info to proceed.

**Comment by asadsahi** [comment]
Closing it for now, if you got any more issues, please raise it with a sample repo. Thanks
