### ISSUE TITLE
Slow loading

### ISSUE THREAD

**Issue by mayorquin** [asadsahi/AspNetCoreSpa#174]
First of all, I want to thank you, for your excellent work in this template.
Everything works perfect but I'm having some problems with the slow loading.

When I ran the project in VS2017, the chrome browser launches quickly but it took about 3-4 minutes load the app... I'm only running the App without any change... 

There is something that I can disable in VS or in the template, to load faster?

Thanks in advance.

**Comment by pvagnini** [comment]
Also thank you for an excellent project template. I can also concur that after moving to the V2.0 template and running with VS2017 I am experiencing very long project load times, which are much longer than previous. This is where the web page sits with the Loading page showing. Once it starts everything works great.

In my case the project is connected to an SQL server database.

Thanks.

**Comment by pvagnini** [comment]
P.S. I have found that sometimes when the project has been sitting at loading. If you stop and do a reload on the browser it starts straight away.

**Comment by asadsahi** [comment]
@mayorquin @pvagnini Thanks for your feedback. Unfortunately the architecture of current master branch is based on previous asp.net core spa template, where client builds (webpack etc) are  part of .net build, so developers have to pay penalty in terms of wait time to complete both builds. So, we have to rely on how .net and webpack brings the optimisation as time progresses.

However, there is a good news. New asp.net core spa template which is based on angular-cli is working in a separate process really improves the performance where both client and server builds will not be strictly dependent on each other. There is already a [branch ](https://github.com/asadsahi/AspNetCoreSpa/tree/angularcli) where work is in progress and I am just waiting to finally release the angular-cli .net extension package to be released before I make that branch as master. That will surely improve the slowness.

Closing this for now as there isn't something which can be done right now. Hope that is OK.
