### ISSUE TITLE
how to setup the project from scratch

### ISSUE THREAD

**Issue by Cuiqs76** [asadsahi/AspNetCoreSpa#175]
would you provide the steps to setup the project from scratch?

**Comment by asadsahi** [comment]
@Cuiqs76 this is quite abstract question. Can you please elaborate a little what do you mean by setting up project from scratch? Do you mean how to setup a project from blank slate?

**Comment by Cuiqs76** [comment]
Yes , from blank slate.

If use vs 2017  netcore 2.0 angular template ,  it's different to your project. 
I know I can copy some file of this project to my project such as .angular-cli.json 、webpack.config.vendor.js etc.  but I don't think this is no good way to setup project

**Comment by asadsahi** [comment]
@Cuiqs76 VS angular template isn't blank template either, it has some libraries/components pre-added. This SPA template is an extended version of that which has even more stuff into it. If you want to start with a blank slate, start from Visual studio empty template and then add anything which suits your requirement.

You can always take things out from any existing template (this template or VS angular template) if that helps.
