### ISSUE TITLE
Data Service

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#176]
@asadsahi 
i need two things.
1. can you please guide me what wrong with this code.
    this.dataService.get('api/photo/delete', photoId);
 this.dataService.get<string>('api/photo/delete', photoId);
post request working perfectly
get request not working. i also try to pass object instead of photoId but not working.

2. simple notification
am trying to use your simple notification but its to easy can you please give me quick easy ho to show my errors in notification or may i implement my own version using angular tostify?

on you live sample when user try to register again its shows messages in notificaiton user already exists etc how you using this notification? plz give me direction

my project is near to complete using your template proejct

**Comment by asadsahi** [comment]
@sajidali2444 

Response to your points:

1. You should use photo id in delete url rather 2nd parameter in delete method, see examples [here](http://www.restapitutorial.com/lessons/httpmethods.html).

2. You can disable global error handler at [this](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/app/core/core.module.ts#L61) line. and manually call notifications service methods (success, error, warn etc). An example can be found [here](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/app/account/%2Bprofile/user-info/user-info.component.ts#L45).
