### ISSUE TITLE
where can i get client_id ?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#179]
Dear @asadsahi 
Please guide me where can i get client id in file auth.config.ts
I try : "aspnetcorespa", "498770901095-mrabuie6uo3he6p5s7sf0hjvq3a3j6po.apps.googleusercontent.com"
My google api, it have a error : The specified 'client_id' parameter is invalid

**Comment by asadsahi** [comment]
@meninjanho4788 client_id in auth.config.ts is for openidconnect application identifier, which should match with with ClientId property of OpenIddictApplicationDescription config. check SeedDbData.cs around line 111. This is nothing to do with google client_id or client_secret keys.

Having said that. google secrets you have need to be configured in appsettings.json file.

**Comment by meninjanho4788** [comment]
Dear @asadsahi 
Thank you so much

**Comment by asadsahi** [comment]
@meninjanho4788 you are welcome. Closing for now.
