### ISSUE TITLE
After registering the user, I can't login, here's there error.

### ISSUE THREAD

**Issue by eddyekofo94** [asadsahi/AspNetCoreSpa#183]
<img width="900" alt="screen shot 2017-12-19 at 16 01 30" src="https://user-images.githubusercontent.com/12385031/34166093-f194224a-e4d5-11e7-8097-b96095152404.png">

**Comment by pvagnini** [comment]
Have a look at my issue #180 where I describe the fix to this issue.

Regards

**Comment by asadsahi** [comment]
@eddyekofo94  [this ](https://github.com/asadsahi/AspNetCoreSpa/commit/505e47a6a3145802d15c46ab70a6a84fee3afc1c) should fix it.

@pvagnini  you are right there was a breaking change in recent version of openidconnect package. I have to add new migration in master to fix it.
 
Closing for now, but if you find any more issues let me know.

Thanks
