### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#184]
@asadsahi 
hi
again one problem please help
this is not working
import { Injectable } from '@angular/core';
import { UtilityService } from './utility.service';
import { NotificationsService } from '../../core';

@Injectable()
export class PostService {
    constructor(
        public us: UtilityService,
        private ns: NotificationsService) { }
public setPackageDetail(packageId: number) {
        this.ns.success('Success', 'Your Ad posted');
    }
}
notification service not working nothing happens not error even.
can you give me direction what am doing wrong?

**Comment by asadsahi** [comment]
@sajidali2444 I don't know your project in details. Follow [this example](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/app/account/+profile/user-info/user-info.component.ts#L52) to follow along?

**Comment by sajidali2444** [comment]
@asadsahi 
Thank you for quick response @asadsahi 
Exactly I am following your provided project template.

I already see this link you mentioned but this is from component but my requirement is from service class to show a message.

I want to show message from my service which not working.
your demo project working.

should I use this.ns.alert() in subscribe method?
 
this is my service file where I want to trigger message
import { Injectable } from '@angular/core';
import { DataService } from '../services/data.service';
import { GlobalRef } from '../global-ref';
import { Observable } from 'rxjs/Observable';
import { IPostModel } from '../../shared/models/post.model';
import { Router } from '@angular/router';
import { UtilityService } from './utility.service';
import { NotificationsService } from '../../core';

@Injectable()
export class PostService {
    private readonly postAdUrl = 'api/PostAd';
    postDetail: IPostModel;
    postsData: IPostModel[];
    constructor(
        private readonly router: Router,
        private readonly dataService: DataService,
        private readonly globalRef: GlobalRef,
        public us: UtilityService,
        private ns: NotificationsService) { }
    public setAdDetail(adDetail: IPostModel) {
        this.postDetail = adDetail;
        this.router.navigate(['/post/packages']);
    }
    public setPackageDetail(packageId: number) {
        this.ns.success('Success', 'Your Ad posted');
        this.router.navigate(['/post/finish']);
        // return this.dataService.post<IPostModel>(`${this.postAdUrl}/postad`, data);
    }
    public loadLatestPosts() {
            Observable.of(this.globalRef.nativeGlobal.appData.posts).subscribe(c => {
                this.postsData = c as IPostModel[];
            });
    }
    public getPostById(postId: number) {
        return this.dataService.get(`${this.postAdUrl}/GetAdDetailById/${postId}`);
    }
}

**Comment by asadsahi** [comment]
@sajidali2444 have you tried debugging? can you step into the notifications service call to see if it is going inside that function?

**Comment by sajidali2444** [comment]
@asadsahi 
Thank Asad.
Eventually, i solved my notification issue its due to my HTML Header which was overlapping on the notification now I change notification position to bottom working perfectly.
thanks for your support and appreciate your timely help.

**Comment by asadsahi** [comment]
Glad you fixed it @sajidali2444
