### ISSUE TITLE
API tests

### ISSUE THREAD

**Issue by sergot** [asadsahi/AspNetCoreSpa#187]
Hi!

This repo is great! Thank you for your work! :)

The only thing I think is missing is: unit tests for the API.

Any plans for this?

**Comment by asadsahi** [comment]
@sergot thanks for suggestion. I would love to add unit tests. It just requires project to shuffle a little. Make this multi project solution to keep api unit tests separate from web project. would do at some point.

**Comment by asadsahi** [comment]
Added framework for unit tests but don't have time to add unit tests for existing functionality. Happy for someone to take this challenge and merge PR when ready.
