### ISSUE TITLE
Issue when setting locally Social login 

### ISSUE THREAD

**Issue by elcondedebahia** [asadsahi/AspNetCoreSpa#189]
After setting facebook Id's I get this issue every time:

error:invalid_request
error_description:The specified 'redirect_uri' parameter is not valid for this client application.

this is the request URL:
http://localhost:5000/connect/authorize?response_type=id_token%20token&client_id=aspnetcorespa&state=ipfAqg1LUk1BEkmDXIlNotDJQXxL34PSVpLj9aON&redirect_uri=http%3A%2F%2Flocalhost%3A5000&scope=openid%20profile%20email%20offline_access%20client_id%20roles&nonce=ipfAqg1LUk1BEkmDXIlNotDJQXxL34PSVpLj9aON&provider=Facebook

I guess I'm missing a configuration but I can't find wich. Can you give me a hint? Thanks

**Comment by elcondedebahia** [comment]
Solved by removing trailing slash from the redirect URI in the DB:
from
http://127.0.0.1:5000/
to
http://127.0.0.1:5000

Hope someone else find this useful.

**Comment by mrandreev** [comment]
Hi @elcondedebahia 

Did you remove just trailing slash and keep everything like it was? Because I have exactly the same problem and your solution doesn't fix it. Maybe there is something else?

Thanks :)

**Comment by elcondedebahia** [comment]
Did you make that change in the DB? Also did you change the application ID in the code and also in the DB? Let me know.
