### ISSUE TITLE
favicon not working

### ISSUE THREAD

**Issue by nicolasmeier** [asadsahi/AspNetCoreSpa#19]
the file `wwwroot/favicon.ico` does not work / is corrupted

**Comment by nicolasmeier** [comment]
i suggest using [this]( https://angularjs.org/favicon.ico)

https://angularjs.org/favicon.ico

**Comment by crh225** [comment]
Can be closed with merge

**Comment by asadsahi** [comment]
@nicolasmeier Thanks for identifying.
@crh225 Thanks for fixing.
