### ISSUE TITLE
Refresh token and role and permission in angular 4

### ISSUE THREAD

**Issue by nyghtrocker** [asadsahi/AspNetCoreSpa#190]
Hi, 
Thanks for the great solution and it helps me a lot. How to do refresh token and check role, permissions in angular 5? any idea?

**Comment by asadsahi** [comment]
> How to do refresh token
there are two piece to this. Server side refresh token functionality is enabled. Check [this](https://github.com/asadsahi/AspNetCoreSpa/blob/master/Server/Extensions/ServiceCollectionExtensions.cs#L101) . For client side you need to write some code which refreshes token. 

In fact there is another branch of this project (look ssr branch) where oidc + refresh token functionality is implemented using [angular-oauth2-oidc](https://github.com/manfredsteyer/angular-oauth2-oidc) library, where doing refresh is a single line. I am planning to make that as master very soon. so I would encourage to check that out.

> How to do refresh token and check role, permissions in angular 5? any idea?

Id token has this information including users' use [this](https://github.com/asadsahi/AspNetCoreSpa/blob/master/ClientApp/app/core/services/account.service.ts#L22) function from account.service.ts
