### ISSUE TITLE
How to let users register with their Facebook accounts?

### ISSUE THREAD

**Issue by nyghtrocker** [asadsahi/AspNetCoreSpa#194]
Do you have any method in AspNetCoreSpa app that let user register or create a local account using social logins?

**Comment by asadsahi** [comment]
@nyghtrocker have you looked at [this](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup) wiki?

**Comment by asadsahi** [comment]
closing for now. Please let me know if you find any issues after following the wiki.
