### ISSUE TITLE
SSR Timeline

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#195]
Hi Asadsahi,

I note in the project features list that you now list SSR as coming soon.

Are you able to give any approximate timing for this at this point please? I am deciding if I should wait before upgrading some existing apps or just use the current new cli version.

Regards
Paolo

**Comment by asadsahi** [comment]
@pvagnini this project is based on same new cli version, but there are few issues with it. See [this](https://github.com/asadsahi/AspNetCoreSpa/issues/55#issuecomment-359108577) discussion. You can give it a shot with cli and share your experience.
