### ISSUE TITLE
duplicated account.service.ts

### ISSUE THREAD

**Issue by kmiskiewicz** [asadsahi/AspNetCoreSpa#196]
Hi Asad, the project gets better and better. Really amazing job!  
I pulled the latest changes and I noticed that account.service.ts exist in two places: 
1. AspNetCoreSpa/ClientApp/app/core/services/account.service.ts
2. AspNetCoreSpa/ClientApp/src/app/core/services/account.service.ts

Is it correct?

Best regards,
Krzysztof

**Comment by asadsahi** [comment]
@kmiskiewicz thanks for letting me know.

I believe the first one isn't needed. I have removed and checked in.
