### ISSUE TITLE
Routes not including the Base Url

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#197]
Hi @asadsahi,

In the non Cli version the I was able to use a service something like;
private GetAssetByIdApi = 'api/Asset/GetAssetById/';
public GetAssetById(id: number) {
        return this.dataService.post(this.GetAssetByIdApi, +id);
    }

This no longer works in the Cli version. However is I append the BaseUrl to the start of  'api/Asset/GetAssetById/' it does work.

Can you please explain why the difference in the 2 branches please?

Regards Paolo.

**Comment by asadsahi** [comment]
@pvagnini register.component.ts is using dataservice by passing similar endpoint and it works as expected without passing base_url. can you double check your endpoints are configured as register or if you can spot any difference?

**Comment by pvagnini** [comment]
I have just re-downloaded the current Master and installed. The register function does not work. 
Same with things like the user-info also does not work. I can login O.K. with one of the pre-installed users such as admin@admin.com
I do note that all this works in your example at your link http://aspnetcorespa.azurewebsites.net/
although I should point out that it only works if you change to https, so perhaps you should change the link.

**Comment by asadsahi** [comment]
@pvagnini I suspect this could be related to [this](https://github.com/asadsahi/AspNetCoreSpa/issues/198)

Do you wanna try again. remove your node_modules first.

Thanks

**Comment by pvagnini** [comment]
Hi @asadsahi,

I have downloaded and started fresh from the current project. The Resgister now works, but a minor thing is that the IsEnabled for the user is set to false.

However the login now does not work. It does not hit the AuthorizationController and returns the following message;

Error: Uncaught (in promise): HttpErrorResponse: {"headers":{"normalizedNames":{},"lazyUpdate":null},"status":400,"statusText":"Bad Request","url":"http://localhost:5000/connect/token","ok":false,"name":"HttpErrorResponse","message":"Http failure response for http://localhost:5000/connect/token: 400 Bad Request","error":{"error":"unauthorized_client","error_description":"This client application is not allowed to use the token endpoint."}}

Regards Paolo.

**Comment by pvagnini** [comment]
Hi @asadsahi,

After doing some more digging the issue appears to relate to changes to OpenIdDict in version 2.0.0-rc2-0802 where there has been changes to the database structure.

I have deleted the database and migrations and then created a new Initial Migration, but the endpoint is being refused with the details below. This same issue also effect to Non-Cli branch when created from scratch.

fail: OpenIddict.OpenIddictProvider[0]
      The token request was rejected because the application 'aspnetcorespa' was not allowed to use the token endpoint.
fail: OpenIddict.OpenIddictHandler[0]
      The token request was rejected with the following error: unauthorized_client ; This client application is not allowed to use the token endpoint.
info: OpenIddict.OpenIddictHandler[0]
      The token response was successfully returned: {
        "error": "unauthorized_client",
        "error_description": "This client application is not allowed to use the token endpoint."
      }.

I have searched for an answer but to no avail so far.

Regards Paolo.

**Comment by asadsahi** [comment]
@pvagnini there was a breaking change in openidconnect package which was updated and fixd in the migrations of this project.  So the work you have done to update migrations is correct. 

I believe with correct login details you must be able to login, but if you enter incorrect login details you get this response:

```
{"error":"invalid_grant","error_description":"The username/password couple is invalid."}
```

...which currently isn't being handled on the client properly (which I will have a look)

Can you confirm if that isn't the case?

**Comment by pvagnini** [comment]
Hi @asadsahi,

I am definitely using a correct login. As I posted before the AuthorizeController is never being hit, so the password is never checked.

What I have found is that if I run from the dotnet command line rather than through Visual Studio I get some extra error information. In this case is definitely shows that the endpoint is being rejected because 'aspnetcorespa' was not allowed to use the token.

At this point I would suggest that as well as changing some database structure something else has changed or been broken.

**Comment by pvagnini** [comment]
I have confirmed that if I downgrade the openiddict packages to 2.0.0-rc-0797 then the login works fine.
Also I am able to navigate to my Controllers with the correct navigation URL like  'api/Asset/GetAssetById/'.

**Comment by PinpointTownes** [comment]
@asadsahi apps must now be granted permissions to be able to use an OIDC/OAuth2 feature. To fix the error reported by @pvagnini, you'll have to update [`AddOpenIdConnectOptions`](https://github.com/asadsahi/AspNetCoreSpa/blob/master/Server/SeedDbData.cs#L102):

```csharp
var descriptor = new OpenIddictApplicationDescriptor
{
    ClientId = "aspnetcorespa",
    DisplayName = "AspnetCoreSpa",
    PostLogoutRedirectUris = { new Uri($"{host}signout-oidc") },
    RedirectUris = { new Uri(host) },
    // Add these lines:
    Permissions =
    {
        OpenIddictConstants.Permissions.Endpoints.Authorization,
        OpenIddictConstants.Permissions.GrantTypes.Implicit
    }
};
```

Cheers

**Comment by asadsahi** [comment]
@PinpointTownes cannot resolve Permission property.

![image](https://user-images.githubusercontent.com/3470892/35759188-edd40252-086f-11e8-8bd0-dfb118919603.png)

**Comment by PinpointTownes** [comment]
Did you restore? These things are included in the latest version.

FYI I wrote a migration guide: https://openiddict.github.io/openiddict-documentation/guide/migration.html

**Comment by asadsahi** [comment]
Ahhh, apologies, had to restore form non-nuget feed :)

Sorted through [this](https://github.com/asadsahi/AspNetCoreSpa/commit/9fb4eab30979ae2d5ed30030ba98d2aafce7cbbc).
