### ISSUE TITLE
Routing doesnt work on refresh

### ISSUE THREAD

**Issue by layinka** [asadsahi/AspNetCoreSpa#198]
Hi,
I am currently using the current master branch and running it on my dev server.
The routing works properly if i navigate first to the home page and then follow the links.

But if i try to access any page from the address bar directly, it seems the app takes that page as the base url,and takes it to be the home page i.e If i navigate to http://localhost:5000/login directly, it renders the home page not the login page and then all links become relative to http://localhost:5000/login e.g. http://localhost:5000/login/chat and therefore they don't work

**Comment by kmiskiewicz** [comment]
I had the same issue but I modified the project a bit so I wasn't sure if it was a problem with mine code after merge or with the project itself. As a workaround I added In  ClientApp/src/main.ts, but I don't understand why it has a problem to read it from index.html (  <base href="/" />)

 const providers = [
     { provide: APP_BASE_HREF, useValue: '/' }, // you have to add this line, but again, it's a workaround
     { provide: 'BASE_URL', useFactory: getBaseUrl, deps: [] },
Add a comment to this line
 ];

**Comment by asadsahi** [comment]
@layinka  @kmiskiewicz there was an issue with angular-cli which is fixed in [this](https://github.com/angular/angular-cli/commit/b17a629) commit, I will be pushing in a fix in this project in a bit.

**Comment by asadsahi** [comment]
[this](https://github.com/asadsahi/AspNetCoreSpa/commit/4f6e655f22b36268943c46a84514941965ecd9d5) should fix it.
