### ISSUE TITLE
FontAwsome fonts not working

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#199]
Hi @asadsahi,

The FontAwsone fonts will not load.

Chrome debug reports;
GET http://localhost:5000/fonts/fontawesome-webfont.ttf?v=4.7.0 404 (Not Found)

**Comment by asadsahi** [comment]
@pvagnini font-awesome aren't included by default now. You need to follow [cli wiki](https://github.com/angular/angular-cli/blob/master/docs/documentation/stories/include-font-awesome.md) to add them in this project.

**Comment by asadsahi** [comment]
@pvagnini sorry, didn't realise that font-awesome are still being used in this project. There seems to be an issue with latest version of angular cli (i.e 1.7.0-beta3). I have raised an issue with them. Raised an [issue](https://github.com/angular/angular-cli/issues/9496) with cli team.

**Comment by pvagnini** [comment]
Thanks @asadsahi,

I think there may be some issues with boostrap in general as well.

Currently page renders as this;
![image](https://user-images.githubusercontent.com/30579629/35766686-452b4962-0928-11e8-9273-4dc827ee294f.png)

Exact same code in previous non-cli version renders as this;
![image](https://user-images.githubusercontent.com/30579629/35766738-50f36f4e-0929-11e8-9e8e-4ead157b8dcf.png)

**Comment by asadsahi** [comment]
@pvagnini what bootstrap version are you on? Can you confirm if markup + classes you are using are as per latest bootstrap version. ( You can refer to latest bootstrap examples too ).  There were a lot of changes from alpha to beta transition.

**Comment by pvagnini** [comment]
Thanks @asadsahi, you are correct. Another change required with the new verions.
Project moved from Bootstrap v4.0.0-beta.2 to Bootstrap v4.0.0

This means the Boostrap structure for input groups moves from this;
<div class="input-group">
                <span class="input-group-addon">User</span>
                <input type="text" class="form-control" id="userfilter" placeholder="Filter Text"
                       [(ngModel)]="usersearch.searchtext" (keyup)="enterPress($event)" focus="true" />
                <span class="input-group-btn">
                    <button type="button" class="btn btn-info btn-s"
                            (click)="loadusers()">
                        <i class="fa fa-search" aria-hidden="true"></i>
                        Load
                    </button>
                </span>
            </div>

To this;
<div class="input-group">
                <div class="input-group-orepend">
                    <span class="input-group-text">User</span>
                </div>
                <input type="text" class="form-control" id="userfilter" placeholder="Filter Text"
                       [(ngModel)]="usersearch.searchtext" (keyup)="enterPress($event)" focus="true" />
                <div class="input-group-append">
                    <button type="button" class="btn btn-info btn-s"
                            (click)="loadusers()">
                        <i class="fa fa-search" aria-hidden="true"></i>
                        Load
                    </button>
                </div>
            </div>

We still have the issue with FontAwsome.

Thanks for your help.

**Comment by pvagnini** [comment]
Hi @asadsahi,

I  note with your last project changes that the FontAwsome fonts still don't work, but the error reported in Chrome appear to have changed to;
**_Failed to decode downloaded font: http://localhost:5000/fontawesome-webfont.68560c510686599ffbc9.woff2?v=4.7.0_**

**Comment by asadsahi** [comment]
@pvagnini [this](https://github.com/asadsahi/AspNetCoreSpa/commit/8717a2056694c05605d305b52248e81ef7a16e3a) should fix it.
