### ISSUE TITLE
non-cli can't run

### ISSUE THREAD

**Issue by BunyodUz** [asadsahi/AspNetCoreSpa#202]
Hi @asadsahi,
Thank you for great template!

I got a problem with non-cli version.
I'm getting this:

ERROR in [at-loader] ./ClientApp/app/core/services/api-translation-loader.service.ts:7:14 
    TS2420: Class 'ApiTranslationLoader' incorrectly implements interface 'TranslateLoader'.
  Types of property 'getTranslation' are incompatible.
    Type '(lang: string) => Observable<StringMap[]>' is not assignable to type '(lang: string) => Observable<any>'.
      Type 'Observable<StringMap[]>' is not assignable to type 'Observable<any>'.
        Property 'source' is protected but type 'Observable<T>' is not a class derived from 'Observable<T>'.

**Comment by asadsahi** [comment]
@BunyodUz I experienced this on windows 7 machine but while running on windows 10 I can't see this error. Trying to identity the different on these environments. Which env are you on?

BTW, I would encourage you to switch to cli version if there isn't a huge concern. Performance of running cli version of project is largely improved as well.

**Comment by asadsahi** [comment]
Closing it for now on the bases of more information needed.
