### ISSUE TITLE
Route back to login when Unauthorised access

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#204]
Hi @asadsahi,

When a Token is not valid the global-error.service produces a notification of Unathorised which is good.

Is there also a way to route back to the Login screen automatically when this happen please?

Regards Paolo

**Comment by asadsahi** [comment]
@pvagnini [here ](https://github.com/asadsahi/ngnode-fullstack/blob/master/src/app/core/services/global-error.service.ts#L12)is your clue.

Happy to have a pull request :)
