### ISSUE TITLE
Fix swagger

### ISSUE THREAD

**Issue by Trojaner25** [asadsahi/AspNetCoreSpa#206]
Please add `Microsoft.AspNetCore.StaticFiles` >= 2.0 to fix it.

Related https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/483

**Comment by asadsahi** [comment]
@Trojaner25 have you encountered any issue with current swagger implementation?

**Comment by Trojaner25** [comment]
Yes, altough I fixed it for myself using this

**Comment by asadsahi** [comment]
@Trojaner25 swagger page is currently visible without this package. Have you tried running the project in current state and see what isn't appearing and elaborate the issue in a little detail.

**Comment by Trojaner25** [comment]
I will close the issue if its visible now (it was completely broken for me back then, but maybe I broke something?)
