### ISSUE TITLE
always showing this Cannot GET /

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#208]
any help please its showing me  Cannot GET / i added new folder dashboard and dashboard.component.ts and html file.
not error in console how I can debug this problem.?

**Comment by asadsahi** [comment]
@sajidali2444 you need to provide much more details when asking questions or raising an issue. 

If you are having an issue with any parts of application or something that you are building, the depth of understanding to which anyone can have guesses is minimal without looking at what the error is. The error that you are describing is quite abstract and not sure what can cause a get request to fail. 

Please share a reproduction repo or elaborate on the issue. Closing it for now until more information is provided. Hope that is ok.
