### ISSUE TITLE
SignlR broken on demo site

### ISSUE THREAD

**Issue by crh225** [asadsahi/AspNetCoreSpa#210]
Hi Asad,
When I go to the demo site, and type any message, I am getting the following error:
![image](https://user-images.githubusercontent.com/19475195/37429675-115b9eb8-279e-11e8-9bbb-42b86a36a4a3.png)

**Comment by asadsahi** [comment]
@crh225 it should be fixed as part of this https://github.com/asadsahi/AspNetCoreSpa/commit/cb241be7de16176fb3d43433598ac76fe8adf05f and site is good for chat demo as well.
