### ISSUE TITLE
Multiple Apps

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#225]
@asadsahi 
hi i created admin app inside clientapp folder when i try to run admin app using ng serve admin  its throwing error like Option 'paths' cannot be used without specifying '--baseUrl' option.
simple ng serve working fine perfectly but i need another app admin panel in clientapp which is not working can you guide me what i am doing wrong.
as the official documentation says just create another app using ng generate an application in existing projects folder and use ng serve app2 to run but it is not working

please help.

**Comment by asadsahi** [comment]
closing as it is off topic.
