### ISSUE TITLE
App is not running on IE 11

### ISSUE THREAD

**Issue by Vencalekl** [asadsahi/AspNetCoreSpa#228]
App is not running on IE 11, it looks that there is an polyfils.js issue. Could you check it out please?

**Comment by asadsahi** [comment]
@Vencalekl have you tried uncommenting the appropriate [polyfills](https://github.com/asadsahi/AspNetCoreSpa/blob/master/src/AspNetCoreSpa.Web/ClientApp/src/polyfills.ts)? What specific issue are you having? Can you provide more details?

**Comment by Vencalekl** [comment]
Thank you @asadsahi for your message, I did not try to uncomment the appropriate polyfills, will try and let you know. I guess that will do the trick.

**Comment by asadsahi** [comment]
Possible issue with enabling polyfills. Escalate if there is any further issues.
