### ISSUE TITLE
OpenId auth, client validation failed because 'https://localhost:44364/' was not a valid redirect_uri for app

### ISSUE THREAD

**Issue by Vencalekl** [asadsahi/AspNetCoreSpa#229]
There is a mismatch between what is stored to db as redirect uri, in my case - ["http://localhost:5000"] and what is then used as comparison value from open id manager, in my case it is https://localhost:44364/ which is the iiSettings ssl port with domain. 
Thank you in advance for checking this out. 

Lukas

**Comment by asadsahi** [comment]
@Vencalekl this issue must have be fixed with some new changes in the project, this is a configurable entry of STS server now in appsettings.json.
