### ISSUE TITLE
karma: if there is a unit test error, there is somewhat of a hard landing of karma

### ISSUE THREAD

**Issue by martinoss** [asadsahi/AspNetCoreSpa#23]
![image](https://cloud.githubusercontent.com/assets/2587942/17810719/18310f58-661f-11e6-9a84-dfe2be8a5653.png)

**Comment by crh225** [comment]
@martinoss, how are you running the tests? what does **karma start** ?

**Comment by nicolasmeier** [comment]
@crh225 he is runnig `npm run start`

**Comment by crh225** [comment]
When I would run the actual karma command, it always runs better than with the npm commands.

**Comment by nicolasmeier** [comment]
here is the output from `karma run`
![karma-start](https://cloud.githubusercontent.com/assets/19802619/17811213/d9476988-6621-11e6-944b-7ad0a4d039eb.png)

**Comment by nicolasmeier** [comment]
[silencing errors on failures for npm run script](http://stackoverflow.com/questions/26814034/silencing-errors-on-failures-for-npm-run-script)

**Comment by crh225** [comment]
@asadsahi, should we close this?

**Comment by asadsahi** [comment]
@crh225 closing it for now as above seems solution to avoid errors.
