### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by pvagnini** [asadsahi/AspNetCoreSpa#235]
Hi @asadsahi 

Is there are reason that Bootstrap is not included in the latest version of this project please?

Regards
Paolo

**Comment by asadsahi** [comment]
@pvagnini trying to keep minimal opinion on styling the app. Saw different trends about styling (bootstrap/material/custom etc). I have copied the scss source from [milligram](https://milligram.io/) in this project which is really small css framework. this gives a very light version of styling which can be customised if someone wants. Or if someone wants to add bootstrap or material, they can do that as well.
