### ISSUE TITLE
Passwordless Login

### ISSUE THREAD

**Issue by kmiskiewicz** [asadsahi/AspNetCoreSpa#241]
Hi Asad 

I hope you are well, The problem which I have most probably is out from the scope of the project so feel free to just close the issue...however I'd be grateful for a hint

I'd like to implement passwordless login to the application, I have implemented already a custom token provider based on this [article](https://andrewlock.net/implementing-custom-token-providers-for-passwordless-authentication-in-asp-net-core-identity/) but I got stuck because I have no clue how to utilize the token which I generated and how to use this token to login user into to the application. 
I'm very sorry for bothering you with such issues but I really got stuck and I couldn't find anything straightforward on the internet. Could you give me a hint?

Best regards,
Krzysztof

**Comment by asadsahi** [comment]
@kmiskiewicz sorry for the delay, but I have never worked with such authentication TBH.

If you are having a specific error, share your code and I can try and have a look.
