### ISSUE TITLE
Loading User Profile from Social Provider?

### ISSUE THREAD

**Issue by isaac2004** [asadsahi/AspNetCoreSpa#242]
Hey there, I am trying to figure out the best way to get the user profile from the social provider. I know oidc has a loadUserProfile() function, but I am not sure where to call it in the flow. My goal is to get the email and name (possibly profile photo) from the provider and create the profile without asking the user to provide an email. Their name would also be written to the Identity DB. Is there a best place to put this code?

**Comment by asadsahi** [comment]
@isaac2004  apologies for the delay.

The way I understand any information from oauth server can be exposed and requested through client with a list of scopes. Some default claims are exposed and more can be requested when setting up application and these additional scopes will be listed on the consent screen when user logs in, like a permissions list on a mobile app.

Never tried myself apart form the default claims social providers expose, but I can certainly try if you are still struggling with some code.

Closing this for now, but let me know if I can be of any more help.
