### ISSUE TITLE
Identity Server Help

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#247]
Hi Asad,
Thanks for your support,
I need help if you please guide me or give me your valuable direction.
i need identity server 4 inside .net core API project I mean in a single project.
I try to merge your project in API project but nothing happened.
my need is I have iOS and Android app and admin panel in angular 7 so .net core API will provide data to all apps as well as authentication and protect API too.
one thing more I have my own login and registration pages in the angular and mobile app. so i don't want identity server login pages.
how I can achieve it?
please help.
Appreciate your suggestion or some resource or links.

**Comment by asadsahi** [comment]
@sajidali2444 it sounds like you are looking for in app login which still exist in this branch for the project. https://github.com/asadsahi/AspNetCoreSpa/tree/openid-connect
