### ISSUE TITLE
Dependency Issues - jquery, popper.js, Angular 6

### ISSUE THREAD

**Issue by tparikka** [asadsahi/AspNetCoreSpa#248]
Hello,

I got the warnings below when running npm install:

```
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none is installed. You must install peer dependencies yourself.
npm WARN preboot@6.0.0-beta.6 requires a peer of @angular/common@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN preboot@6.0.0-beta.6 requires a peer of @angular/core@^6.0.0 but none is installed. You must install peer dependencies yourself.
```

I currently have Angular 7.1.4 installed - would I need to downgrade to 6.0.0 to support this solution? Also, should these packages be included in the packages.json file as dependencies?

**Comment by asadsahi** [comment]
@tparikka ignore some of these warnings. Peer dependencies of some packages are different, but what gets built is agains your local npm package versions and their peer dependencies, so only one version will be built in final bundle.
