### ISSUE TITLE
Identity server migration

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#249]
Hi @asadsahi can you please help 
i am trying to migrate the database to MySql on MAC Machine
following error occurred during migration

An error occurred while accessing the IWebHost on class 'Program'. Continuing without the application service provider. Error: MAC verification failed during PKCS12 import (wrong password?)
Unable to create an object of type 'PersistedGrantDbContext'. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
i follow readme file but no success and also try ApplicationDbContext as alternative same error

**Comment by fr4nk-dev** [comment]
You include this nuget package?

MySql.Data.EntityFrameworkCore.Design

**Comment by sajidali2444** [comment]
@fr4nk-dev  still same error after adding MySql.Data.EntityFrameworkCore.Design
i also replace UseSqlite with MySql and added packages Pomelo.EntityFrameworkCore.MySql,Pomelo.EntityFrameworkCore.MySql.Design but it still throwing error at migration time

**Comment by asadsahi** [comment]
@sajidali2444 just pushed a branch with mysql implemented in web project. Identity server can follow the same. Let me know if that helps.
 Check this comparison

https://github.com/asadsahi/AspNetCoreSpa/compare/mysql?expand=1

**Comment by sajidali2444** [comment]
@asadsahi Thanks I already managed it and its working and also push my code to Azure.
one thing still not working on my MAC machine "Error: MAC verification failed during PKCS12 import (wrong password?)" this due to the certificate which you provided in app settings. 
for temporary i AddDeveloperSigningCredential  certificate option. could get some time to check why this is not working of Mac book pro.

**Comment by asadsahi** [comment]
@sajidali2444 AddDeveloperSigningCredentials will get you going, but not recommended for the production scenarios. Didn't come across such error before so no idea. Sorry. Closing this issue for now as you have managed to get it working.

**Comment by sajidali2444** [comment]
Thank you Asad bahi
certificate  error on MAC still there but it is working on AWS Linux Server with Nginx web server. i tried to generate my own self signed certificate but no success i think something wrong in .net core framework because lots of discussions are there on github.
just awaiting for .NET Core 3 version support.
