### ISSUE TITLE
login-redirect.html missing

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#253]
@asadsahi can you please help me 
after login on redirect error occurred no route found with login-redirect.html

![image](https://user-images.githubusercontent.com/960620/59542550-ef1e2880-8f1f-11e9-9f13-226c4cc02a48.png)

**Comment by asadsahi** [comment]
If this issue is still valid, please create a minimal reproduction and link here and I might have a look. Thanks
