### ISSUE TITLE
MAC verification failed during PKCS12 import

### ISSUE THREAD

**Issue by exbarboss** [asadsahi/AspNetCoreSpa#266]
During step 7 of Installation getting the following exception when trying to run ID server project on Mac:
`Unhandled exception. Interop+AppleCrypto+AppleCommonCryptoCryptographicException: MAC verification failed during PKCS12 import (wrong password?)
   at Interop.AppleCrypto.X509ImportCertificate(Byte[] bytes, X509ContentType contentType, SafePasswordHandle importPassword, SafeKeychainHandle keychain, Boolean exportable, SafeSecIdentityHandle& identityHandle)`

Exception is thrown at line 51 of Startup.cs class
``` C#
cert = new X509Certificate2(base64EncodedStr, string.Empty, X509KeyStorageFlags.MachineKeySet);
```

**Comment by asadsahi** [comment]
[this](https://github.com/asadsahi/AspNetCoreSpa/commit/86c877467eb094fd5e838e7ea8fe9292af3ca421) should fix.
