### ISSUE TITLE
Update to RC6

### ISSUE THREAD

**Issue by crh225** [asadsahi/AspNetCoreSpa#27]
RC6 is now out for angular 2

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/18181124/569dee7a-704f-11e6-9d8a-d34226da3c8a.png)

**Comment by crh225** [comment]
These might need to be updated as well with rc6 release
![image](https://cloud.githubusercontent.com/assets/19475195/18181156/7d4c2b90-704f-11e6-8b19-6dce22e4ec1a.png)

**Comment by asadsahi** [comment]
@crh225  Upgraded to RC6 now.
