### ISSUE TITLE
Template config for streams

### ISSUE THREAD

**Issue by weedkiller** [asadsahi/AspNetCoreSpa#276]
Hello, can you share what configurations need to be made to this if we want to stream Video or Continuous  such as long range

**Comment by asadsahi** [comment]
@weedkiller difficult to propose some configuration for such scenarios, however it looks like asp.net core supports it already, have a look at this answer:
https://stackoverflow.com/a/59593869/1190512

Closing it for now, but feel to have a PR if you think there could be a useful example we can add in this for streaming videos. :)
