### ISSUE TITLE
Live Demo not working

### ISSUE THREAD

**Issue by chibuagu** [asadsahi/AspNetCoreSpa#29]
I tried accessing the live demo for this application but found an error on the page.

**Comment by nigel-dewar** [comment]
My too. Its not working.

**Comment by asadsahi** [comment]
@chibuagu @nigel-dewar This is something to do with how azure is handling the deployment, investigating.

**Comment by asadsahi** [comment]
Have setup CI with VSTS, also in the process of setting up with appveyor. Demo should be working now.
