### ISSUE TITLE
app.component.ts:23 Uncaught Error: Cannot find module "./app.component.scss"(…)

### ISSUE THREAD

**Issue by crh225** [asadsahi/AspNetCoreSpa#3]
I get an error when following the install instructions and then running via command line.
app.component.ts:23 Uncaught Error: Cannot find module "./app.component.scss"(…)

Im sure something is not installed on my system. Any help would be greatly appreciated!

**Comment by crh225** [comment]
I had to run npm install node-sass sass-loader raw-loader --save-dev

**Comment by asadsahi** [comment]
I have changed from require syntax to url based loading of html and scss files using angular2-template-loader now.

Glad you resolved it though. :+1:
