### ISSUE TITLE
webpack prod build

### ISSUE THREAD

**Issue by crh225** [asadsahi/AspNetCoreSpa#31]
webpack prod build does not work currently.

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/18591560/bb4a4116-7bf8-11e6-9a42-fc9c2af4ad27.png)

**Comment by crh225** [comment]
![image](https://cloud.githubusercontent.com/assets/19475195/18591611/e56e5cfc-7bf8-11e6-9b66-e70c2ad5c4f5.png)

**Comment by asadsahi** [comment]
@crh225 follow the latest npm scripts in the project, they don't require webpack to install globally and prod build is created using **npm run build:prod** command
