### ISSUE TITLE
Invalid configuration object.

### ISSUE THREAD

**Issue by curlyfro** [asadsahi/AspNetCoreSpa#32]
i'm getting this error after i

`npm run build:vendor`

C:\websites\AspNetCoreSpa>npm run build:vendor

> aspnetnetcore@0.0.0 build:vendor C:\websites\AspNetCoreSpa
> node node_modules/webpack/bin/webpack.js --config config/webpack.config.vendor.js

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve.extensions[0] should not be empty.

**Comment by asadsahi** [comment]
@curlyfro there were some breaking changes introduced in webpack beta 23, I have pinned down webpack to beta 22 in master to void breackages. Can you get latest and try again?

Thanks

**Comment by curlyfro** [comment]
cool -- it works :)
thx
