### ISSUE TITLE
My SQL Server Express experience

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#33]
I changed the database engine to SQL Server Express by 
	(a) Changing the DefaultConnection in appsettings.json
	(b) Changing the ApplicationDBContext options in Startup.cs to UseSQLServer (instead of UseSQLLite).

I found I had to make the following changes to your entities to enable SeedData to work with SQL Express.

```
  public class Language : IEntityBase
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
	  …
     }

    public class Content : IEntityBase
    {
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.None)]
        public int Id { get; set; }
        …
     }
```

**Comment by crh225** [comment]
@asadsahi you can probably close this.

**Comment by kiwiingenuity** [comment]
@crh225 Rather than just closing it... Why not add the two lines of code to your project first?

**Comment by asadsahi** [comment]
If there is any issue regarding this project, feel free to open it.
