### ISSUE TITLE
Dynamic forms issue

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#37]
The Register Component uses dynamic forms.
If you look at the register.component.ts the controls are set up to query username, firstname, lastname, email and password.  However if you look at the live demo [http://aspnetcorespa.azurewebsites.net/register/registerhome](http://aspnetcorespa.azurewebsites.net/register/registerhome) you see that only email and password appear on the view.  Why is that?

**Comment by asadsahi** [comment]
Should be fixed now. If not, try cache bust js files with Ctrl  +  F5.
