### ISSUE TITLE
Where to add custom CSS

### ISSUE THREAD

**Issue by albrookesplowman** [asadsahi/AspNetCoreSpa#40]
Hi,

I have based a project on this template as it is exceptionally easy to understand.  However, I am wanting to add in a 3rd party library and CSS - called DevExtreme by DevExpress.

I have added their package into the package.json file so that it gets downloaded by NPM - success.
I have added the control into the HTML file - success.
I have added the import into the TS file - success.

However, the appears is not correct as I am not sure of the best place to include their CSS files.  I have tried various things with the webpack files and when I did managed to get their controls to appear correct, the bootstrap css doesn't appear to work.

Do you have an example of how to configure this template for 3rd party CSS and libraries.  Many thanks

**Comment by asadsahi** [comment]
try added CSS/SCSS files in vendor.ts from node_modules directory:

**// e.g ../node_modules/libraryname/dist/file.scss
//or
//// e.g ../node_modules/libraryname/dist/file.css**

Vendor file will look like this:
```
// Add third party css/scss files here:
// e.g ../node_modules/libraryname/dist/file.scss
//or
//// e.g ../node_modules/libraryname/dist/file.css

// Angular 2
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/forms';
import '@angular/http';
import '@angular/router';
.............
```

**Comment by albrookesplowman** [comment]
I have added the 3rd css files to the vendor.ts but the controls do not have the necessary appearance when they are displayed in the home component page.

Do I also need to reference the CSS in one of the HTML/TS files that relate to the home page?

**Comment by asadsahi** [comment]
can can you share the code?

**Comment by albrookesplowman** [comment]
i can zip it all up without the node_modules if it helps

**Comment by albrookesplowman** [comment]
as all i have done so far is take this project and add the DevExtreme packages for angular 2 and added a dx-button onto the home page which should show a button but it doesn't

**Comment by asadsahi** [comment]
can you upload on github?

**Comment by albrookesplowman** [comment]
i am afraid that i haven't got that far and created a github repository for it yet. but once i have i will let you know

**Comment by albrookesplowman** [comment]
I think that I have create one here:

https://github.com/albrookesplowman/angular

**Comment by albrookesplowman** [comment]
I have trying putting the CSS in the styleurls parameter in the component as well but now the error regarding "expected 'styles' to be an array of strings".

It all seems a bit confusing

**Comment by asadsahi** [comment]
Closing this one as there isn't any issue with the project.

**Comment by asadsahi** [comment]
@albrookesplowman I tried running your project but got some runtime issues. 

I have updated readme to have clear instructions. There are new commands to run after npm install. Can you grab the latest code and add same packages to see any difference?
