### ISSUE TITLE
Adding NPM packages

### ISSUE THREAD

**Issue by kiwiingenuity** [asadsahi/AspNetCoreSpa#41]
This question is similar to the previous question…

I'm still struggling with WebPack?  I thought an example may help me understand better…

I would like to add a modal view to the application.  There is a bunch to choose from but I have selected "https://www.npmjs.com/package/ng2-bs4-modal".  I'm struggling how to include this package into the application and I was wondering if you would show me/us be example?

Would you please consider adding this package and publishing an update so that the process can be better understood?

TIA

**Comment by asadsahi** [comment]
The project is using ng-bootstrap (official ui bootstrap library by angular ui team). That has a modal component in it. I would suggest trying that as you don't have to add any other library.

As an example see [this ](https://github.com/asadsahi/ng2fb-bootstrap/blob/master/src/app/%2Badmin/product/product.component.ts#L45)bit of code in [one ](https://github.com/asadsahi/ng2fb-bootstrap)of my other playground project.

**Comment by kiwiingenuity** [comment]
That was a good example!  Thank-you.
I note that that example uses Object.assign()
That appears to be a very useful function.
I tried using it in the project, but the command was not recognized.
Is that because we are using es5?
