### ISSUE TITLE
JWT or Cookies authentication?

### ISSUE THREAD

**Issue by asadsahi** [asadsahi/AspNetCoreSpa#43]
In single page applications JWT makes more sense to me. Just wanted to hear from people what they want in this project? JWT or Cookies based authentication? 

Right now we have Cookies authentication implemented.

**Comment by lecnierfreeman** [comment]
Hi,
I clone your project and added a basic JWT middleware  to .NET Core server side and started adding the angular part, I think bearer token auth is better today because you can support different kind of clients,  web, mobile, desktop and other external request to the server side, and the gain from the complexity added is worth it.

**Comment by asadsahi** [comment]
@lecnierfreeman great to hear that. I am thinking [Openiddict](https://github.com/openiddict/openiddict-core) a better fit for JWT implementation because of its simplicity.

**Comment by crh225** [comment]
we are using https://github.com/IdentityModel/oidc-client-js for the client
and Identity server: https://github.com/IdentityModel/IdentityModel

**Comment by FacundoGFlores** [comment]
What about Identity Server?
https://github.com/IdentityServer/IdentityServer4

**Comment by asadsahi** [comment]
@FacundoGFlores what is benefit of using IdentityServer over Openiddict. Probably a detailed discussion, but in terms of simplicity and implementation.

What I am thinking of added just token generation and authentication in this project rather relying on seperate client and server libraries. Also, having a simple password flow which directly authenticates from an endpoint and send token to the client (angular 2 in our case) to pass back for api authentication and authorisation etc.

**Comment by crh225** [comment]
When I said we were using IdentitModel, I meant we are using IdentityServer as well. I only set up the client side though, and not the server itself.

**Comment by asadsahi** [comment]
Hi guys, just to update, I am implementing jwt in another branch called jwt to implement token based authentication. That branch will bring quite a number of other improvements like improved DLL support and Angular 2 AOT compilation etc. I am planning to merge that into master. Stay tuneds !!! :)

**Comment by asadsahi** [comment]
JWT is new master branch now.
