### ISSUE TITLE
typings and adal

### ISSUE THREAD

**Issue by albrookesplowman** [asadsahi/AspNetCoreSpa#46]
I am trying to incorporate angular 2 ADAL into this template using:

https://github.com/alenny/angular2-adal-example/

but I get the following error as desribed with their issue:

https://github.com/alenny/angular2-adal-example/issues/2

However, if this spa template that you have created, there isn't a typings.json file.... Do I simply add it to the custom-typings.d.ts file or is there something I am missing?

many thanks

**Comment by asadsahi** [comment]
This project is using typescript 2 which added support for typings as npm packages. if you see package.json, thats where are the typings exist now. So if you try adding adal typings as a node package in package.json file, see if error goes away.

**Comment by asadsahi** [comment]
Closing for now.
