### ISSUE TITLE
version script calls non-existent build script

### ISSUE THREAD

**Issue by Ketrex** [asadsahi/AspNetCoreSpa#47]
This is more a question, than an issue. 

In package.json there is a "version" script which calls "npm run build." No build script exists in the project, so an error occurs. I have encountered this in other packages, is this an intentional omission or should there be a build script present?

**Comment by asadsahi** [comment]
@Ketrex Not using these scripts in any build pipeline. Initially some of these exist as inspiration from angular2-webpack-starter project :)

I have removed some unnecessary script in jwt branch to simplify the list for dev/test/prod scenarios. They should be available in master after merge.
