### ISSUE TITLE
publish options for a production build

### ISSUE THREAD

**Issue by albrookesplowman** [asadsahi/AspNetCoreSpa#48]
I am trying to create a production build with publish and CI but in the project.json file there is the publishoptions:

  "publishOptions": {
    "include": [
      "appsettings.json",
      "Client",
      "Views",
      "tsconfig.json",
      "web.config",
      "config",
      "wwwroot"
    ]
  },

For a production build, can I simple use:

  "publishOptions": {
    "include": [
      "appsettings.json",
      "tsconfig.json",
      "web.config",
      "wwwroot"
    ]
  },

**Comment by asadsahi** [comment]
@albrookesplowman Sure, if it suits your need. I think some extra files are there if we are using server side rendering then we need to copy node_modules + any other necessary files. This project isn't using server side angular 2 rendering, so makes sense to simplify what to include in build.

**Comment by albrookesplowman** [comment]
Thanks for the update - do you know how to add the server side rendering?  I have to tried to see the differences between this project and another one I found but I have not been able to add this feature

**Comment by asadsahi** [comment]
I am holding back for SSR (Server side rendering) right now as things aren't as stabilise as they have to be. So, no idea, sorry :)
