### ISSUE TITLE
Please add example login, create login Facebook?

### ISSUE THREAD

**Issue by meninjanho4788** [asadsahi/AspNetCoreSpa#50]
Please guide me one example login social. FB

**Comment by asadsahi** [comment]
@meninjanho4788 [this ](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup)wiki should point you to right direction.

**Comment by meninjanho4788** [comment]
When i recomment 
app.UseFacebookAuthentication(new FacebookOptions()
 {
     AppId = Configuration["Authentication:Facebook:AppId"],
     AppSecret = Configuration["Authentication:Facebook:AppSecret"]
 });

In Debug, code run to function ExternalLoginCallback of (AccountController)
and result is :

return Render(ExternalLoginStatus.CreateAccount); ==> and Stopped!
How i redirect continue to page CreateAccount for run function ExternalLoginCreateAccount

excuse me ! i am newbie. hard to learn MVC and angular 2
