### ISSUE TITLE
Unable to get AOT working

### ISSUE THREAD

**Issue by Krishna-teja** [asadsahi/AspNetCoreSpa#52]
I tried "npm run build:aot" and then "dotnet run". Its having errors in console log that vendor.css is missing. Am I missing something?

Thanks!

**Comment by asadsahi** [comment]
@Krishna-teja AOT isn't fully implemented yet as lazy loading isn't working with webpack in aot mode yet. I am preparing the project slowly towards AOT. So stay tuned :)

**Comment by crh225** [comment]
@asadsahi has there been any update on this?

**Comment by valentinmarinro** [comment]
Hi @asadsahi, any new development on aot compilation?

**Comment by asadsahi** [comment]
@valentinmarinro @crh225 @Krishna-teja I have done some work in AOT in a seperate branch called netcore2. There are alot of changes in .net core 2 which until its not released, will  not make it to master. AOT and SSR are part of those changes as well. Thought to update you guys.

**Comment by asadsahi** [comment]
Hi guys, master is on .net core 2 now which has AOT build support in it. Give it a go, let me know if you encounter any issues. Thanks
