### ISSUE TITLE
Project doesn't run

### ISSUE THREAD

**Issue by j-nord** [asadsahi/AspNetCoreSpa#53]
We get follow error:
The program '[13320] dotnet.exe' has exited with code -2147450751 (0x80008081).

and where we can find the database:  Data Source=AspNetCoreSpa.db ?

We have done everything according to instructions.

**Comment by asadsahi** [comment]
@j-nord are you using Visual studio IDE or VS code? You just need to do F5 in these two.

If you are using commandline you need to first set dev environment:

**set ASPNETCORE_ENVIRONMENT=Development**

then do 
**dotnet run**

**Comment by j-nord** [comment]
We use Visual Studio 2015.

**Comment by asadsahi** [comment]
Never seen this issue, can you let me know environment details?

**dotnet info** ?

node -v
npm -v

**Comment by j-nord** [comment]
PM> node -v
v7.5.0
PM> npm -v
4.1.2

**Comment by asadsahi** [comment]
Try with latest 6.x node version as state in readme. haven't tried this under node v7.x.

**Comment by askpt** [comment]
It's working on my machine with that node version... So probably could be something related with the dotnet installation.

**Comment by asadsahi** [comment]
@j-nord can you attach some screenshot or further details for this issue as I am unable to guess any reason for above issue.

**Comment by j-nord** [comment]
In Visual Studio we get follow error in Output:

The program '[20928] dotnet.exe' has exited with code -2147450751 (0x80008081).
The program '[8000] iisexpress.exe' has exited with code 0 (0x0).

**In the event-protocol from windows:**

Failed to start process with commandline '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe" -debug -p "C:\Program Files\dotnet\dotnet.exe" -a "E:\Users\Juergen\Documents\Visual Studio 2015\Projects\AspNetCoreSpa-master\bin\Debug\netcoreapp1.1\AspNetCoreSpa-master.dll" -pidFile "C:\Users\Juergen\AppData\Local\Temp\tmpD954.tmp" -wd "E:\Users\Juergen\Documents\Visual Studio 2015\Projects\AspNetCoreSpa-master"', ErrorCode = '0x80004005'.

**We have found a perfect example which work's fine without any problems from chsakell**:

[https://github.com/chsakell/aspnet5-angular2-typescript](url)

**Comment by asadsahi** [comment]
@j-nord I can see project running under following visual studio IDE without any error.

![image](https://cloud.githubusercontent.com/assets/3470892/23064268/04f1f1ba-f507-11e6-8dff-eed5c30acf2c.png)

It could be your particular environment. Have you tried switching to node 6.9,x? You can use [NVM ](https://github.com/creationix/nvm)to easily switch between different versions of nodejs.

**Comment by maksir** [comment]
@j-nord if you download project as *.zipfile, try to follow steps:
1. Close VS
2. Rename folder from 'AspNetCoreSpa-master' -> 'AspNetCoreSpa'
3. Remove 'node_modules' folder
4. Open VS and wait when 'restore dependencies' completed
5. F5

I helped it. But after run I see only 'fa-spinner', no errors in chrome console, no errors in VS.
I try past /home url, /registration url.... but see only spinner, it's all.

**Comment by BitFlipp3r** [comment]
@maksir 
Its probably an unnecessary question, but just in case: Do you have JS enabled?

**Comment by maksir** [comment]
@BitFlipp3r yes. I have many a angular2 projects, all works OK.

**Comment by maksir** [comment]
after command 'npm run clean:dist' and F5 again all work now.
