### ISSUE TITLE
Some issues i have found.

### ISSUE THREAD

**Issue by javietanh** [asadsahi/AspNetCoreSpa#56]
Dear,

I got some issues when running your template.
1/ External login not working (please give some guide on how to setup the login on google or facebook, the guide from Microsoft is old)
2/ Maybe DbSeed not running. nothing on database.
3/ Change namespace and dll name -> IIS express could not be run with visual studio.

- Can i switch to Mysql database?

Viet Anh,
Cheers

**Comment by asadsahi** [comment]
@javietanh I have just tried the social login for google and redirection happend successfully. Have you gone through the [wiki](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup)? I have updated slightly to point to the right file where the social login code is commented out.

The article from microsoft still seems to be appropriate.

Bear in mind that this project just have the framework for social logins, Once the redirection is successfull, you need to be responsible for how you manage the registration of the user etc.

If you have any specific issue to discuss, please let me know and we can discuss further.
