### ISSUE TITLE
watch and compile on fly problem

### ISSUE THREAD

**Issue by najimtab** [asadsahi/AspNetCoreSpa#57]
I tried "npm run dev" and "donet watch run" and when I tried to modify a component template (just html part) but the page doesnet get update on executing F5 in the browser and nothing logged in the commandline console.

 I have to execute npm run build:prod then donet watch run each time I modify something.

It is possible that I am not executing the correct script?

Thanks

**Comment by asadsahi** [comment]
@najimtab if you are running the project from command line you need to run **dotnet run** or **dotnet watch run** commands after setting following variable:

`set ASPNETCORE_ENVIRONMENT=Development`

This will run webpack dev middleware , that runs applications under HMR (Hot module replacement).

Note: If you are running the project with Visual studio IDE or visual studio code then you don't need to set environment variables.  F5 should run under dev mode.
