### ISSUE TITLE
Authentication on the homepage

### ISSUE THREAD

**Issue by robertpmansion** [asadsahi/AspNetCoreSpa#60]
Quick question: how do you properly add the authentication on the home page?

I tried the below codes but the `canActivate: [AuthGuard]` does not work on the homepage but in the rest of the routes works perfectly fine.

I also tried some of the suggestions I found on the internet but would not work on the homepage.

```
import { Routes, RouterModule } from '@angular/router';
import { AuthGuard } from './core/auth-guard/auth-guard.service';

const routes: Routes = [
    { path: '', redirectTo: 'home', pathMatch: 'full' },
    // Lazy async modules
    {
        path: 'login',
        loadChildren: './+login/login.module#LoginModule'
    },
    {
        path: 'register',
        loadChildren: './+register/register.module#RegisterModule'
    },
    {
        path: 'home',
        loadChildren: './home/home.module#HomeModule',
        canActivate: [AuthGuard]
    },
    {
        path: 'profile',
        loadChildren: './+profile/profile.module#ProfileModule',
        canActivate: [AuthGuard]
    }
];
```

**Comment by asadsahi** [comment]
@robertpmansion have you tried adding [AuthGuard] on home.routes.ts?

**Comment by robertpmansion** [comment]
@asadsahi it does work when I add it to home.routes.ts, but do I have to set to every route like profile.routes.ts? any more efficient where I could just set them in one place?

**Comment by asadsahi** [comment]
@robertpmansion it depends on your scenario, you need to have a public page for sure, where users can land on , and you don't want to puth authguard on that landing page. if you are thinking end users to land on login page by default, then you can set login page as default landing page without auth guard and secure all other routes using authguard. 

An efficient way to handle that could be  to hook into routing events rather putting authguard agains each route. Something like this:

http://stackoverflow.com/questions/33520043/how-to-detect-a-route-change-in-angular-2

Bear in mind that you still need to check that landing page ins't included in this check.

**Comment by robertpmansion** [comment]
@asadsahi thank you. I will try this. :)
