### ISSUE TITLE
Translate!

### ISSUE THREAD

**Issue by javietanh** [asadsahi/AspNetCoreSpa#61]
Dear,

Sorry but how does angular-translate work? where is the lang .json file?

Viet Anh,
Cheers

**Comment by asadsahi** [comment]
@javietanh this project is loading translations from server after user changes language instead of static json file.

Implementation is here:

https://github.com/asadsahi/AspNetCoreSpa/blob/master/Client/app/shared/services/api-translation-loader.service.ts

**Comment by m2017atTR** [comment]
Hello,
Regarding to documentation, injecting translation module and service could be in app module.
It s working on shared module but not in admin module components.

Have you faced with this issue ?

Mehmet
Cheers
