### ISSUE TITLE
Social registration

### ISSUE THREAD

**Issue by quanterion** [asadsahi/AspNetCoreSpa#62]
Are you planning to implement social registration via facebook, google etc?
You are currently using ASP.NET Core external auth. So you end up using JWT for Username/password and cookies for Facebook and other providers. Are you going to change this and use JWT only and exchange google or facebook tokens for your JWT token, so you are using your own JWT token only.

**Comment by asadsahi** [comment]
@quanterion good question.

I have implemented this in few other nodejs based project where I have a strategy to send back token from server after oauth verification in query string and client can store that token as they have logged in. total cookie free solution. 

Will look at implementing at some point.

**Comment by layinka** [comment]
Hi,
I ma having a little challenge with this, after login in with facebook, it redirects me to account/accessdenied ad then it gives me the error below.

_Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'Account/AccessDenied'_

**Comment by layinka** [comment]
Hi, Does anyone have a solution to this yet?

**Comment by meninjanho4788** [comment]
Please help us this issue with login FB, Google

**Comment by kmiskiewicz** [comment]
Anyone was successful with social registration?

**Comment by meninjanho4788** [comment]
no i am not, i waiting

**Comment by kmiskiewicz** [comment]
Check the newest version, right now is at least two steps further. After social login the account is created and user can be sign in by signin manager (C# side). I think the Angular part left.

**Comment by asadsahi** [comment]
@kmiskiewicz thats right, only part left is token generation and send it to client to auto login after social account creation.

**Comment by asadsahi** [comment]
@kmiskiewicz @meninjanho4788 @layinka @quanterion Finallay, I have managed to get something working. I have also update the [wiki](https://github.com/asadsahi/AspNetCoreSpa/wiki/Social-Login-Setup) to describe how to set them up. Give it a try and let me know if you find any issue.

Enjoy :)
