### ISSUE TITLE
Question on Visual Studio 2017 compatibility

### ISSUE THREAD

**Issue by meteor-learning** [asadsahi/AspNetCoreSpa#63]
First, this is an amazing starter template, and the first one I've found that has CLI support with .NET core, which is what I was looking for.  I attempted to have Visual Studio 2017 do an automatic upgrade, but the openid packages break and nuget can't restore the packages.  With the official release of Visual Studio 2017 coming out in just a few days, do you plan on providing an outline or best steps on how to do this and converting this over to csproj format?  So far I haven't been successful and will probably continue using Visual Studio 2015, but was hoping to use Visual Studio 2017 with it.  Thanks, Tim

**Comment by rakeshrohan** [comment]
@meteor-learning 
you have to manually add the following nuget package sources under
**Tools->Nuget Package Manager ->Package sources.** 
1) https://www.myget.org/F/aspnet-contrib/api/v3/index.json
2) https://dotnet.myget.org/F/aspnetcore-ci-dev/api/v3/index.json

restore the packages and rebuild now. It should work.

**Comment by meteor-learning** [comment]
Awesome, that worked perfect!  A huge help.  Now I can use this in Visual Studio 2017.  Thanks!  Tim

**Comment by asadsahi** [comment]
upgraded to csproj with final release of dotnet sdk 1.0.0. Most of the project dependencies been upgraded as well. Let me know if you encounter any more issues.
