### ISSUE TITLE
Compile with More Strict Flags

### ISSUE THREAD

**Issue by hillin** [asadsahi/AspNetCoreSpa#65]
Hi, this is a great SPA. I wish it could compile with the following typescript flags turned on:

- [ ] `noUnusedLocals`: there are many unused local variables
- [ ] `strictNullChecks`: variables cannot be `null` or `undefined` unless they are so declared 
- [ ] `noImplicitAny`: variables cannot be implicitly be type of `any`
- [ ] `noImplicitReturns`: all execution paths must return a value in non-void-returning functions

Since Angular 4 is becoming compatible with these flags, it will be great if this SPA do, too. In fact, as an SPA, it is always good to be as strict as possible, so the users can feel free to turn these options on or off in their own favor.

**Comment by hillin** [comment]
Although, due to some bugs of current Angular 4 build (rc3, [see bug here](https://github.com/angular/angular/issues/14677)), `strictNullChecks` is still not entirely possible.

**Comment by asadsahi** [comment]
@hillin Thanks for feedback. I will look into these in more details. However today I have upgraded project o csproj and alot of tslint been fixed according to angular guidelines. Project is using angular 4 rc now. Can you give it a go and let me know couple of places where these features aren't being implemented to have a better understanding?

Thanks

**Comment by hillin** [comment]
@asadsahi I've synchronized with your update. This issue has nothing to do with tslint, just set those options to true in tsconfig.json, build the project in Visual Studio and you can see errors in the Error List panel.

For example, in [base-comment.ts](https://github.com/asadsahi/AspNetCoreSpa/blob/master/Client/app/%2Bexamples/component/change-detection/base-comment.ts):

```typescript
public comments = [];
```
should be changed to 
```typescript
public comments = new Array<Comment>();
```
otherwise the following code will raise an error if `strictNullChecks` is on:
```typescript
this.comments.push(comment);
```
because in such case, `comments` is of type `never[]` rather than `Comment[]`, which is expected.

**Comment by asadsahi** [comment]
@hillin thanks for your feedback.

If I set this option in tsconfig.json, I am not getting this caught in tslint, but do get red squigly lines in vscode, and as you mentioned in VS IDE as well. So I would expect this to be part of tooling as well, so that we can get this tested in deployment / production workflow. 

Any thoughts on that?

**Comment by hillin** [comment]
@asdsahi actually it's typescript compiler (tsc) who does the job, and maybe the so-called intellisense is also involved. If you turn on these options, the code won't compile.

**Comment by hillin** [comment]
I've added `noImplicitReturns` into the list as well, which enforces all execution paths to have a return value in non-void-returning functions and methods.

**Comment by asadsahi** [comment]
@hillin I have turned all the above flags on and updated project with most of the fixes. Still not 100% there for couple of reasons:

* Ideally I would like to apply as many types as possible to our classes/variables as possible. But its a good start. Still we have alot of any type variables.
* I have to turn these two options on to get around something that tsc command was checking in @angular/forms module
```
"skipDefaultLibCheck": true,
    "skipLibCheck": true,
```

Let me know if you find anything which is missing.

Thanks

**Comment by hillin** [comment]
@asadsahi I've merged your commits into our project and it worked like a charm! Great job!
