### ISSUE TITLE
Renaming project

### ISSUE THREAD

**Issue by MartinSher** [asadsahi/AspNetCoreSpa#71]
Hi

Thanks for the template.

I am trying to bring it into a VS2017 solution and want to rename the project.  After renaming I get errors as per below when rebuilding the solution.

Unable to resolve 'Microsoft.AspNetCore.SignalR.Server (>= 0.2.0)' for '.NETCoreApp,Version=v1.1'.		

Any ideas as to how to rename it.

Thanks
Martin

**Comment by asadsahi** [comment]
@MartinSher try removing following line from AspNetCoreSpa.csproj file and then reloading project:

https://github.com/asadsahi/AspNetCoreSpa/blob/master/AspNetCoreSpa.csproj#L49

I think this is leftover from another branch. Will remove it and push it soon.

**Comment by MartinSher** [comment]
Thanks
It does work but then I need to comment out references to SignalR in the code.

Similar problems with OpenIddict references which prevent compile. Works when delete the following lines but then again need to comment out code in the app.

 <PackageReference Include="OpenIddict" Version="1.0.0-*" />

    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="1.0.0-*" />

    <PackageReference Include="OpenIddict.Mvc" Version="1.0.0-*" />

**Comment by asadsahi** [comment]
@MartinSher I can understand signalr problem as it wasn't being used in the master branch. I tried to implement in signalr branch of this project, but them I decided not to put this version of signal r into master as microsoft is working on another project for websockets. I am waiting for it to come out before start integrating into this project for few examples. I have removed all references of signalr now.

For opeiddic.mvc package there is another feed used. Check Nuget.config file at the root of the project. Can you make sure when you try to restore packages, you have All option selected in nuget feed?

**Comment by MartinSher** [comment]
HI
Thanks
Sorry not sure what you are suggesting. 
The project rebuilds fine as the provided. However, when I rename the project then it does not rebuild  with errors

Unable to resolve 'OpenIddict.Mvc (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.		
Unable to resolve 'OpenIddict (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.	
Unable to resolve 'OpenIddict.EntityFrameworkCore (>= 1.0.0)' for '.NETCoreApp,Version=v1.1'.		

When I look under "Manage NuGet Packages" for the "Installed" packages for those 3 it says "Not available in this source". This only appears for these packages.

Any ideas as to what the problem could be.

Thanks
Martin

**Comment by MartinSher** [comment]
Hi 
To reproduce in VS2017.

1. Unzip project in folder \test\
2. Open project
3. Save .sln in \test
4. Rebuild and run -> all OK
5. Rename project in soln -> can't rebuild

Thanks
Martin

**Comment by MartinSher** [comment]
Just following up on this issue to see if anyone has ideas on how I can rename the project and have it compile.
Thanks
Martin

**Comment by asadsahi** [comment]
@MartinSher if you can share your code with this issue, I can try to have a look.

**Comment by SanyaBogos** [comment]
@MartinSher I`ve faced with the same trouble and found a solution. I assume this issue doesn't happen with Visual code. However, if we use VS 2017 it automatically offer us creating a solution (sln) file. Just remove this sln file and open project using csproj. It shoud compile and work fine. (If you wish save sln file, please don't change it`s name and offered directory, click only Save btn. After that you will be able to rename solution and project using VS in Solution explorer with **F2**).

P.S. I also wanted to say a couple of words for creator. @asadsahi that`s great job))) Thank you very much for your project.

**Comment by asadsahi** [comment]
closing this for now. Provide source code with this issue.
