### ISSUE TITLE
problem with "dotnet restore"

### ISSUE THREAD

**Issue by webnegar** [asadsahi/AspNetCoreSpa#72]
accroding to instructions when i use "dotnet restore" in  AspNetCoreSpa folder (step3)
i get this error:
**warn : The folder 'C:\test\AspNetCoreSpa' does not contain a project to restore.**
and
dotnet run
**The current project is not valid because of the following errors:
C:\test\AspNetCoreSpa(1,0): error DOTNET1017: Project file does not exist 'C:\test\AspNetCoreSpa\project.json'.**

**Comment by asadsahi** [comment]
can you provide result of:

**dotnet --info**

**Comment by Azayzel** [comment]
@webnegar can this issue be closed?
