### ISSUE TITLE
Feature: upgrade swagger/swashbuckle

### ISSUE THREAD

**Issue by crh225** [asadsahi/AspNetCoreSpa#75]
Swagger/swashbuckle has been taken out of Swashbuckle and put into an new .net core project https://github.com/domaindrivendev/Swashbuckle.AspNetCore

then namespaces has changed also

**Comment by asadsahi** [comment]
@crh225 Do you know the namespace of 

services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
});

I cannot find c.SwaggerDoc to compile.

**Comment by crh225** [comment]
this is what my startup looks like
```
using Swashbuckle.AspNetCore.Swagger;
using Swashbuckle.AspNetCore.SwaggerGen;
```
```

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "ATLAS Web API", Version = "v1", Description = "Web API generated by CSLA Gen Fork" });
            });
```

**Comment by asadsahi** [comment]
i think visual studio was playing with me. restarted and it worked. Just pushed the changes with new package. see how it goes.

Thanks :+1:
