### ISSUE TITLE
The project works great with the default SQLite, but not with MS SQL Server Express...

### ISSUE THREAD

**Issue by knowshape** [asadsahi/AspNetCoreSpa#76]
Asad,

Thanks much for your response on this problem!  You asked for more detail, so here, below is what I get when I run the project from VSCode.  It's easy enough to see why this happens, but it doesn't seem like the "Seeder" is building a proper SQL Server version, like the SQLite version that works great.

I got the project working, BUT I did it by converting the AspNetCoreSpa.db into AspNetCoreSpa.sql (a SQL Server script), and then methodically running the project against this SQL Server version, until I had worked all the differences in the DDL and SQL out.  

If you have been able to successfully run a MS SQL Server version of this, I would like to know what I'm doing wrong.  However, If you run into the same problem I did, I will be happy to send you my SQL script. :)

--Thanks!,
Richard

Size = 256)], CommandType='Text', CommandTimeout='30']
      SET NOCOUNT ON;
      INSERT INTO [AspNetRoles] ([ConcurrencyStamp], [Description], [Name], [NormalizedName])
      VALUES (@p0, @p1, @p2, @p3);
      SELECT [Id]
      FROM [AspNetRoles]
      WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity();
**fail:** Microsoft.EntityFrameworkCore.DbContext[1]
      An exception occurred in the database while saving changes.
      Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Cannot insert the value NULL into column 'Id', table 'AspNetCoreSpa.dbo.AspNetRoles'; column does not allow nulls. INSERT fails.

**Comment by asadsahi** [comment]
@knowshape can you please mention this details in same issue?

https://github.com/asadsahi/AspNetCoreSpa/issues/73
