### ISSUE TITLE
http://aspnetcorespa.azurewebsites.net/admin without login

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#78]
i could access http://aspnetcorespa.azurewebsites.net/admin without login...
How to prevent some routes ...

**Comment by asadsahi** [comment]
@m2017atTR RouteGuard is what you are looking for. Following is an example you can follow to apply route guard on admin route by checking if user is loggedin. AuthService has a method which can check if user is logged in or not.

http://stackoverflow.com/questions/34331478/angular2-redirect-to-login-page

**Comment by m2017atTR** [comment]
Thanks, works fine...
I can add my changes to repository but dont know how to manage
