### ISSUE TITLE
Translation issue in shared module

### ISSUE THREAD

**Issue by m2017atTR** [asadsahi/AspNetCoreSpa#79]
suggestion :

Translation not working outside shared module...
for work moved 
TranslateModule.forRoot({ loader: { provide: TranslateLoader, useClass: ApiTranslationLoader } })
to app module...
as described in ...
https://github.com/ngx-translate/core/issues/209

**Comment by asadsahi** [comment]
@m2017atTR thanks for pointing out. fixed now.
