### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by mageshbala90** [asadsahi/AspNetCoreSpa#80]
I downloaded the project and restored the dependencies in VS 2017.  When i run the project using VS2017 by F5, it is running in the browser successfully.  But when i edit the html and save, it is not reloading the changes in the browser.  

I am getting the below message in browser console.
**Failed to load resource: net::ERR_CONNECTION_RESET**
Pls help me to resolve this.

**Comment by asadsahi** [comment]
@mageshbala90 can you try removing wwwroot/dist folder and run again to see if it makes any different?

I think you have done npm install without any errors?

**Comment by mageshbala90** [comment]
Hi  @asadsahi ,
The issue is the visual studio solution is closed in the background due to an exception in common.es5.js.  This causes the iis to stop running and produces the "Failed to load resource: net::ERR_CONNECTION_RESET" error.

**Unhandled exception at line 18448, column 5 in http://localhost:5000/dist/vendor.dll.js?v=rYKpEjxEyf-G0grd3roPYLNmfrTdUgY0t6weJb0GNS4

0x800a138f - JavaScript runtime error: Unable to get property 'apply' of undefined or null reference**


Please help me to resolve this error.

Thanks

**Comment by mageshbala90** [comment]
Hi @asadsahi ,

I forgot to uncomment polyfills.. It is working fine now.   I can customize it as my needs.  Thanks a lot for your contribution...

**Comment by asadsahi** [comment]
@mageshbala90 Glad you resolved it.

thanks for kind words. :)
