### ISSUE TITLE
Setup "Options" for Dropdown

### ISSUE THREAD

**Issue by Azayzel** [asadsahi/AspNetCoreSpa#82]
How do I setup the Options for my DropdownControl?

```
import { ControlBase } from './control-base';

export class ControlDropdown extends ControlBase<string> {
    public options: Array<{ key: string, value: string }> = [];

    constructor(options: any = {}) {
        super(options);
        this.type = 'dropdown';
        this.options = options.options || ["Some Option"];

    }
}

```

**Comment by asadsahi** [comment]
@Azayzel what I can see is that you are passing in array of string as default value, but rather you have to pass in array of objects with two properties (key and value), something like this:

```
[
    {key: 'key1', value: 'value1'},
    {key: 'key2', value: 'value2'},
]
```

**Comment by Azayzel** [comment]
Well that code is what i get when i clone the repo (what you see is default). I've tried what you suggest and it still doesn't display anything on screen.

**Comment by asadsahi** [comment]
@Azayzel as an example I have just used this control on registration page for receiving title from user:

![image](https://cloud.githubusercontent.com/assets/3470892/25476925/a2407db2-2b33-11e7-86f5-461339e2e6a7.png)

All I have done is added dropdown control in controls list of registration component:

```
...................
           }),
            new ControlTextbox({
                key: 'password',
                label: 'Password',
                placeholder: 'Password',
                value: '',
                type: 'password',
                required: true,
                order: 5
            }),
            new ControlDropdown({
                key: 'title',
                label: 'Title',
                value: '',
                options: [
                    {key: 'mr', value: 'Mr'},
                    {key: 'mrs', value: 'Mrs'}
                ],
                type: 'dropdown',
                required: true,
                order: 6
            })
        ];
        this.controls = controls;
    }

```

**Comment by Azayzel** [comment]
Ill test this out; i was thinking I had to do this on that class. Thanks!!
