### ISSUE TITLE
.net framework 4.6

### ISSUE THREAD

**Issue by tanwarsatya** [asadsahi/AspNetCoreSpa#85]
while trying to use framework 4.6 its causing error, aspnet core javascript services template works with that. i am trying to migrate my project from that template to yours.

satya

**Comment by crh225** [comment]
This is .Net Core project, not a .net 4.6 project

**Comment by tanwarsatya** [comment]
I understand but is it possible to use 4.6 framework or not because we have certain libraries which are based on full .net framework.

**Comment by asadsahi** [comment]
@tanwarsatya this article explains it how it can work with .net 4.6

https://jonhilton.net/2017/03/14/use-asp-net-core-1-1-with-net-4-without-visual-studio/

But bear in mind that you will only be able to run this project on windows environment after targetting 4.6.
