### ISSUE TITLE
Add global scss for third party components

### ISSUE THREAD

**Issue by MaklaCof** [asadsahi/AspNetCoreSpa#87]
_I am migrating my project from Javascript Services, because I use Kendo UI for Angular which requires Angular 4._
I am trying to add scss ([documentation](http://www.telerik.com/kendo-angular-ui/getting-started/#toc-add-the-styles)).

I add import in main.ts:
`import "../node_modules/@progress/kendo-theme-default/scss/all";`

Do I have to do anything else? Because styles are not imported. 
I read [this](https://github.com/asadsahi/AspNetCoreSpa/issues/40) thread, but can not find vendor.ts file.
I added import in main.ts because of [this](https://github.com/asadsahi/AspNetCoreSpa/issues/59#issuecomment-282749439) thread.

**Comment by asadsahi** [comment]
@MaklaCof because these are 3rd party libraries I would suggest them adding in Client/app/styles/vendor.css file. Or you can create a scss file in that folder and import that scss file in main.ts.

**Comment by m2017atTR** [comment]
Hello ,
I can recomment 

`encapsulation: ViewEncapsulation.None,  `
as described at
[https://github.com/AngularClass/angular-starter/wiki/How-to-include-SCSS-in-components](https://github.com/AngularClass/angular-starter/wiki/How-to-include-SCSS-in-components)

```
import { Component, OnInit, ViewEncapsulation } from '@angular/core';
....
...
@Component({
    selector: 'appc-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss'],  //<-- Collect or import style in this
    encapsulation: ViewEncapsulation.None,  // <-- This saved my day
    // https://github.com/AngularClass/angular-starter/wiki/How-to-include-SCSS-in-components


})
export class AppComponent implements OnInit {
```

hope it helps.
