### ISSUE TITLE
What is 'environment.ts' for?

### ISSUE THREAD

**Issue by skorunka** [asadsahi/AspNetCoreSpa#88]
What is the file `environment.ts` file for?

**Comment by asadsahi** [comment]
@skorunka there are some more optimisations in that file which get applied for production build of angular applications. I stumbled across [this](https://hackernoon.com/everything-you-need-to-know-about-debugging-angular-applications-d308ed8a51b4) article which explains it well. I copied environment.ts file literally from angular2-webpack-starter project. Please not, this file isnt' being used right now. so you can safely delete. But I added this in effort of getting AOT implemented. Hope this clarifies the purpose of this file :)

**Comment by skorunka** [comment]
@asadsahi Will that file be required int he future? Does it mean the AOT is not fully implemented. Thank you. I'm just trying to get my self more familiar with this template as it seems more mature than https://github.com/MarkPieszak/aspnetcore-angular2-universal Thank you.

**Comment by asadsahi** [comment]
@skorunka Thanks for your kind words.

Yes, it isn't implemented yet. But I am playing around with few options to see which one will be suitable to use for AOT, either build own pipeline which will use ngc compiler or to incorporate angular-cli in this project to get aot working. There are few options to explore. There is an open issue for that. So keep an eye on [that](https://github.com/asadsahi/AspNetCoreSpa/issues/52).

**Comment by skorunka** [comment]
@asadsahi Ok, thank you.
