### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#93]
Hi, Thanks 

its works well on localhost without publish. but when i try to publish it localhost iis its not working.
my aim was before go live i want to know either its work on localhost deployment but its not working throwing many wired errors.
again Thanks such as great effort.
steps i do.
1. downloaded  your master and rename your project with my required name like "MyProject"
2. run yarn install or npm install.
3. run dotnet restore
3. @**then try to publish using VS 2017 and its throw error npm clean:build existed with error 0**
can you please help why this happening.
you help will appreciated.

**Comment by asadsahi** [comment]
@sajidali2444 `npm clean:build` doesn't even exist anywhere in the project. Can you confirm if you are working agains master and latest code base.

**Comment by sajidali2444** [comment]
today i downloaded you project and restore packages. run it on local it worked perfectly.
when i try to publish it its throws errors can check image.
could not copy 5.js from dist to because not found.
could not copy 4.js because not found.
![publish](https://cloud.githubusercontent.com/assets/960620/25854134/70fbf970-34e8-11e7-919e-9ac3dfb87b2b.JPG)

**Comment by asadsahi** [comment]
@sajidali2444 If you haven't tried, can you try running visual studio as administrator? As part of publish it run `npm run build:prod` script which deletes wwwroot/dist files and recreates the minified bundles. Looking at the errors it isn't deleteing or building is unable to read them.

**Comment by sajidali2444** [comment]
i always run as Administrator
but still getting publishing error using visual studio 2017
can you please help i want go live project.

**Comment by asadsahi** [comment]
@sajidali2444 if you delete wwwroot/dist folder before publishing it will work. For some reason visual studio publishing remembers the previous dist folder files. This issue doesn't happen if you try from command line using **dotnet publish**.

I raised this issue [here](https://github.com/aspnet/websdk/issues/162) with appropriate team.

**Comment by asadsahi** [comment]
@sajidali2444 https://github.com/asadsahi/AspNetCoreSpa/commit/6cdf6ee0b97f4cec7c0a8f48ebcdd1547bb1d4ae should fix this issue. 

Can you confirm?

**Comment by asadsahi** [comment]
closing this for now as it is fixed.
