### ISSUE TITLE
dotnet resotore and Create Roll Exception

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#94]
please check attachment  i get latest branch run yarn install and dotnet restore
after that db created but create role method throws exception.
![createroles method null value db migration](https://cloud.githubusercontent.com/assets/960620/25847993/e346a0be-34d1-11e7-88ba-b9a1f983c231.JPG)
![dotnet restore](https://cloud.githubusercontent.com/assets/960620/25847992/e3451654-34d1-11e7-853a-8dbdbfab5217.JPG)

**Comment by Azayzel** [comment]
I had this same problem. I created a SQLExpress db first, migrated to that then restored that to SQL db. 

Did you follow the README?

**Comment by sajidali2444** [comment]
i resolved by deleting migrations folder, bin and run dotnet run dropdb command.
