### ISSUE TITLE
Publish Errors

### ISSUE THREAD

**Issue by sajidali2444** [asadsahi/AspNetCoreSpa#95]
again i face publish error but this time it is different last time i face npm run clean:dist error
now it different please check attach image.
![publish](https://cloud.githubusercontent.com/assets/960620/25849384/b2fea8d8-34d7-11e7-817e-d62303d84a58.JPG)

**Comment by asadsahi** [comment]
Linked to https://github.com/asadsahi/AspNetCoreSpa/issues/93 

Can you add details with that issue?
