### ISSUE TITLE
WARNING in ./~/@angular/core/@angular/core.es5.js; 5874:15-36 Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by skorunka** [asadsahi/AspNetCoreSpa#96]
WARNINGs in webpack PROD build cause VSTS builds to fail:

```
WARNING in ./~/@angular/core/@angular/core.es5.js
5874:15-36 Critical dependency: the request of a dependency is an expression
```

**Comment by skorunka** [comment]
See https://github.com/roscoe054

Change `webpack.config.js` (line cca 99):
from `/angular(\\|\/)core(\\|\/)src(\\|\/)linker/,` to `/angular(\\|\/)core(\\|\/)@angular/,`

**Comment by asadsahi** [comment]
@skorunka thanks for pointing out. Fixed and checked in.

**Comment by enriquesouza** [comment]
How can I Update it. I just installed with Aspnet Core SPA.
