### ISSUE TITLE
npm run build:prod issue

### ISSUE THREAD

**Issue by robertcck** [asadsahi/AspNetCoreSpa#97]
Hi, 

I am having issue when publishing the site to IIS. 
The publish process get stuck most of the time at running "npm run build:prod".  It gets stuck or getting out of memory error.

After updating the command in package.json file to 
"build:prod": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js --config config/webpack.prod.js --env.prod"

seems to resolve the issue on my local dev machine and I can start publishing without any issue. (Although it still take ages to get through npm run build:prod process)

However, it does not work on another machine and it just simply hangs forever. I am wondering if there's a way to optimize this process?

**Comment by robertcck** [comment]
A bit more info. 

I am trying to set up continuous build (CI) and deployment (CD) on TFS and the build got stuck on "npm run build:prod"

I tried to run that command on the TFS server manually and got the same result. 

Thanks and looking forward for any comments

**Comment by asadsahi** [comment]
@robertcck never seen this stuck, it takes a while indeed, but the CI I setup on appveyor, builds it as part of publishing:
See the progress here:
https://ci.appveyor.com/project/asadsahi/aspnetcorespa

On my local machine I build both from Visual studio publish which runs `npm run build:prod` in the brackground and `dotnet publish` from command line.

![image](https://cloud.githubusercontent.com/assets/3470892/26016756/4f19a05a-375e-11e7-80e7-17d6618708ab.png)

Do you know at what point in the command line it stucks? Can you let me know your OS, node version?

**Comment by robertcck** [comment]
@asadsahi  Thank you for your response. 

OS is Windows Server 2012 R2 Standard
Node version is v6.10.3

**Comment by robertcck** [comment]
![image](https://cloud.githubusercontent.com/assets/2003517/26020284/f9cf6262-37bf-11e7-85c1-9c390df9e1ed.png)

This is what happen when i try to run it manually from the cmd on the TFS Server

**Comment by kiwiingenuity** [comment]
As a suggestion... Use your favourite search engine and search for "node js scavenge allocation failure".
Perhaps you will find and answer there?

**Comment by robertcck** [comment]
@kiwiingenuity Thanks I will give it a try

**Comment by robertcck** [comment]
TFS build succeed after adding those extra parameters....

"build:prod": "node --max_old_space_size=2048 --optimize_for_size --max_executable_size=2048 --stack_size=2048 node_modules/webpack/bin/webpack.js --config config/webpack.prod.js --env.prod",
