### ISSUE TITLE
Visual Studio cannot restore any of OpenIddict packages

### ISSUE THREAD

**Issue by wendellm** [asadsahi/AspNetCoreSpa#99]
Error	CS0234	The type or namespace name 'OpenIdConnect' does not exist in the namespace 'AspNet.Security' (are you missing an assembly reference?)

**Comment by m2017atTR** [comment]
I think some nuget source definition needed..
in visual studio menu 
     Tools -> options -> nuget ... -> package source 

`https://github.com/asadsahi/AspNetCoreSpa/blob/master/NuGet.config`

also if you are at that situation 
   options -> ... -> external web tools 

location must be ordered for node to use local one for primer if exist

fyi.

**Comment by asadsahi** [comment]
@wendellm unable to reproduce it, try against latest codebase, if problem still persist, please share code with reproduction.
